### ISSUE TITLE
pipeline build fails if no tests run due to archive tap file failure

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#1039]
If a pipeline build is run with tests disabled it fails due to the find *.tap error,
seems related to this PR: https://github.com/adoptium/ci-jenkins-pipelines/pull/1033

https://ci.adoptium.net/job/build-scripts/job/openjdk21-pipeline/285/console
```
ERROR: No artifacts found that match the file pattern "AQAvitTapFiles.tar.gz". Configuration error?
/home/jenkins/.jenkins/jobs/build-scripts/workspace/openjdk21-pipeline@tmp/jfrog/285/.jfrog deleted
Finished: FAILURE
```

**Comment by sophia-guo** [comment]
More notes about https://github.com/adoptium/ci-jenkins-pipelines/pull/1040#issue-2322668769

Interesting there is no alpine-linux tap files, which has the same workspace /home/jenkins/workspace/build-scripts/openjdk11-pipeline. Will take a look

**Comment by sophia-guo** [comment]
Based on the issue mentioned https://github.com/adoptium/ci-jenkins-pipelines/issues/1039#issuecomment-2135453960 and https://github.com/adoptium/ci-jenkins-pipelines/pull/1040#issue-2322668769, I believe access the archived taps from `${env.JENKINS_HOME}/jobs/${env.JOB_NAME}/builds/${env.BUILD_NUMBER}/archive` is a reliable and straightforward approach, which won't mess up with concurrent or parallel builds and former old builds.

**Comment by andrew-m-leonard** [comment]
> > Could find other architecture old build tap files, because only the architecture build that has completed has it's previous content deleted see [ci-jenkins-pipelines/pipelines/build/common/build_base_file.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/ffea6e6e2de7909755628b65595f73f00d6e30dd/pipelines/build/common/build_base_file.groovy#L931)
> > Line 931 in [ffea6e6](https://github.com/adoptium/ci-jenkins-pipelines/commit/ffea6e6e2de7909755628b65595f73f00d6e30dd)
> > context.sh "rm -rf target/${config.TARGET_OS}/${config.ARCHITECTURE}/${config.VARIANT}/"
> > ), which maybe should actually delete eveything to be safe maybe..
> 
> which maybe should actually delete eveything to be safe maybe..- I guess delete everything at this stage may be dangerous as it may delete the new results due to the parallel.
> 
> What's the reason that pipeline job doesn't do cleanWorkspaceBuildOutputAfter to delete all those files since all files have been archived at pipeline post stage?

The cleanWorkspaceBuildOutputAfter is just a build job param, the top level pipeline job has no cleaning, other than what we could add to build_base_file, and I think I agree we should probably do that, ie.cleanWs at the end...
I would also like to see the above pre-worker context clean the whole workspace (in case of a failed|aborted pipeline), as there is no reason to not do that as we  have pointed out you cannot rely on what is in there...I suspect a missunderstanding of this originally was why it was done that way...
@sophia-guo Would you like to try adding this logic please?

**Comment by andrew-m-leonard** [comment]
> Based on the issue mentioned [#1039 (comment)](https://github.com/adoptium/ci-jenkins-pipelines/issues/1039#issuecomment-2135453960) and [#1040 (comment)](https://github.com/adoptium/ci-jenkins-pipelines/pull/1040#issue-2322668769), I believe access the archived taps from `${env.JENKINS_HOME}/jobs/${env.JOB_NAME}/builds/${env.BUILD_NUMBER}/archive` is a reliable and straightforward approach, which won't mess up with concurrent or parallel builds and former old builds.

@sophia-guo yes this is a lot "safer", just one gotcha however, it is possible due to the fact that we only store 1 build output, if for example aarch64 build completes but pipeline is waiting for all the others to complete and say some other independent pipeline runs an aarch64 build job then the build output will be lost by the time the pipeline gets to gathering the *.tap files....
The old "reproducible compare" build (prior to the new system test) would in fact cause this every time.... so I think we should disable/remove the old repro compare option when we do this?
