### ISSUE TITLE
Colour of smoke test block in build pipeline does not reflect failed status correctly.

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#1068]
**What are you trying to do?** Run a build and see the status reflected in the blocks in the pipeline overview

**Expected behaviour:** If the smoke test failes causing an overall fail status in the pipeline, then the corresponding square in the pipeline should show  failed status

**Observed behaviour:**
![image](https://github.com/adoptium/temurin-build/assets/6487691/6c9e1fdf-9e1f-47be-adde-d8a289b509d3)
This screenshot is despite the failure of [riscv64-temurin_SmokeTests#14](https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk/job/jdk-evaluation-linux-riscv64-temurin_SmokeTests/14) triggered by [jdk-evaluation-linux-riscv64-temurin#47](https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk/job/jdk-evaluation-linux-riscv64-temurin/47/console) (it's the overview for jdk-evaluation-linux-riscv64-temurin where the screen shot above was visible)

**Any other comments:**

**Comment by sxa** [comment]
Related:
- https://github.com/adoptium/ci-jenkins-pipelines/issues/234
- https://github.com/adoptium/ci-jenkins-pipelines/issues/11

**Comment by andrew-m-leonard** [comment]
This issue has been frustrating me too! i'm working on a fix
