### ISSUE TITLE
Consider setting GENERATE_JOBS=true when triggering temurin-compliance jobs during EA runs

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#1095]
GENERATE_JOBS calls Test_Job_Auto_Gen to trigger the test jobs to be regenerated.  Setting that parameter to true means that jobs will be using the latest updates to test job parameters.  We already regenerate AQAvit test jobs triggered by EA buiilds, this issue is to also regenerate test jobs on the temurin-compliance Jenkins server.

<img width="168" alt="Screenshot 2024-08-08 at 4 56 02 PM" src="https://github.com/user-attachments/assets/97a72904-b58a-4f62-b903-fcf65e174638">

**Comment by smlambert** [comment]
I believe this is now happening, need to confirm.

**Comment by sophia-guo** [comment]
No, this has not been done. 

To enable this we can set AUTO_AQA_GEN of AQA_Test_Pipeline, which will force [generate test jobs (parents) by job Test_Job_Auto_Gen](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/aqaTestPipeline.groovy#L223-L237) . And will also set GENERATE_JOBS correspondingly to [force generate test child jobs](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/aqaTestPipeline.groovy#L269). 

Tests on temurin-compliance are remotelly triggered by temurin-compliance AQA_Test_Pipeline using Authentication Token. We can set AUTO_AQA_GEN

**Comment by sophia-guo** [comment]
Related https://github.com/adoptium/aqa-tests/issues/5736
