### ISSUE TITLE
Enable reproducible compare tests on PPL64le and Aarch64

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#1114]
Enable reproducible compare tests on PPL64le and Aarch64 so we can get instant test results per tag

**Comment by andrew-m-leonard** [comment]
> Running in grinder @andrew-m-leonard is the result good to go?
> 
> https://ci.adoptium.net/job/Grinder/10964/ https://ci.adoptium.net/job/Grinder/10965/

Yes, both look good, thanks Sophia
