### ISSUE TITLE
Improve build pipeline publish links to warn of build job failures

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#1149]
Arising from retrospective comment: https://github.com/adoptium/temurin/issues/54#issuecomment-2426762664

Improve pipeline publish links in the summary to have a abvious WARNING if the given build job failed.... help potentially publishing a bad JDK by misstake.

**Comment by sophia-guo** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/issues/1148#issuecomment-2491722828 Could we just delete the artifacts for failed build steps and hence do not generate the release link at all?

**Comment by andrew-m-leonard** [comment]
> [#1148 (comment)](https://github.com/adoptium/ci-jenkins-pipelines/issues/1148#issuecomment-2491722828) Could we just delete the artifacts for failed build steps and hence do not generate the release link at all?

I think this is the discussion for the other issue, as to whether we publish regardless, which has been our chosen method to now.
This issue is purely to warn to the fact.

**Comment by sophia-guo** [comment]
For release, there is no reason to publish it.
