### ISSUE TITLE
Request to make Jenkins job permissions configurable

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/ci-jenkins-pipelines#156]
https://github.com/adoptium/ci-jenkins-pipelines/pull/154
https://github.com/adoptium/ci-jenkins-pipelines/pull/155

These 2 PRs introduced changes specific to Adopt that do not apply to other consumers of the Jenkins pipelines. Can these be reworked to be configurable via the defaults.json file? Minimum would be a boolean but ideally also moving the hardcoded team name(s) into the config file.

**Comment by zdtsw** [comment]
theoretically authorizationMatrix can be applied per jenkins instance from "global config" 
so these will be IaC as part of the controller
