### ISSUE TITLE
jtreg artifacts contain incorrect contents 

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#165]
The https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/lastSuccessfulBuild/artifact/jtreg/ job produces several artifacts, some of them contain incorrect contents.   

- jtreg4.2.0 doesn't contain 4.2.0 (see [Slack conversation](https://adoptium.slack.com/archives/C5219G28G/p1623072758038100))
- this job used to produce 5.0.1b but started producing a 6+1 (test.getDependency and job is failing due to this change... was expecting the other version)
- the name of the jtreg 6 file is 'problematic' jtreg--6+1 (and doesn't follow previous naming convention)

The Jenkinsfile and jtreg.sh files are in: https://github.com/adoptium/ci-jenkins-pipelines/tree/master/tools/code-tools

**Comment by smlambert** [comment]
@jerboaa - looking for some assistance with this one if you have time to take it or advise on it, please :)

**Comment by sophia-guo** [comment]
Looking at the code both [`buildJTRegTip()`](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/jtreg.sh#L160) and [`buildJTRegLastTag()`](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/jtreg.sh#L165) are calling [`buildJTReg()`](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/jtreg.sh#L119), which built jtreg by  `make/build-all.sh ["$JAVA_HOME"`](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/jtreg.sh#L141). So no different version information is passed in or considered. All builds (including build using the former scripts  before migrated to github) are building the latest jtreg.

**Comment by sophia-guo** [comment]
This could be fixed by checkout preferred release version https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/Jenkinsfile#L70 https://github.com/openjdk/jtreg/releases

**Comment by jerboaa** [comment]
@smlambert Are you still looking to get this fixed? If yes, I'll take a look later in the week.

**Comment by smlambert** [comment]
If you can, that would be great thanks @jerboaa.

**Comment by jerboaa** [comment]
ok

**Comment by jerboaa** [comment]
Note that JDK head now requires jtreg 6, which isn't backwards compatible. I.e. JDK 17+ will have to use jtreg 6 and other JDKs stay with jtreg 5 (should work for JDK 8 and 11). As such, I'm going to update the code to build jtreg 5 and jtreg 6.

See also:
https://bugs.openjdk.java.net/browse/JDK-8266254

**Comment by smlambert** [comment]
Related: https://github.com/adoptium/aqa-tests/issues/2642

**Comment by sophia-guo** [comment]
I have successful builds available using specific releases https://github.com/openjdk/jtreg/releases https://ci.adoptopenjdk.net/view/work-in-progress/job/GetNode/46/

The tricky thing is the build is build from my personal jtreg branch. https://github.com/sophia-guo/jtreg

The reason for that is jtreg set the latest tagged version by default , which also doesn't support passing in extra tag information: 

```
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 /path/to/jdk/1.8/image" &gt;&amp;2   
   exit 1
fi

get_tag_info() {   
    case $SCM_TYPE in 
        HG)  hg tags | grep jtreg | head -1 ;;   
       GIT) git tag | grep jtreg | tail -1 ;;  
          *) echo "Error: unknown SCM" &gt;&amp;2 ; exit 1 ;;   
   esac
}

## Set version and build numbers to the latest tagged version by default
TAG_INFO=`get_tag_info`<br class="Apple-interchange-newline">

```

https://github.com/openjdk/jtreg/blob/master/make/build-all.sh#L287-L288

https://github.com/openjdk/jtreg/blob/master/make/build-all.sh#L31-L34

https://github.com/openjdk/jtreg/blob/master/make/build-all.sh#L84-L90

So looks like we need to set up a separate repo if we'd like to build versions other than the latest. Thought?

**Comment by jerboaa** [comment]
> So looks like we need to set up a separate repo if we'd like to build versions other than the latest. Thought?

I'm not sure we need to.

@sophia-guo These [two](https://github.com/openjdk/jtreg/blob/master/make/build-all.sh#L289) [lines](https://github.com/openjdk/jtreg/blob/master/make/build-all.sh#L292) look like as if they would respect `BUILD_NUMBER` and `BUILD_VERSION` environment variables. Only if they're **not** set it would use `TAG_INFO`. Have you considered using something like this:

```
# explicitly build jtreg 5.1
export BUILD_NUMBER=b01
export BUILD_VERSION=5.1
bash make/build-all.sh
[...]
```

**Comment by sophia-guo** [comment]
@jerboaa Thanks! Didn't bother to go further once I saw the line [TAG_INFO=`get_tag_info`](TAG_INFO=`get_tag_info`) .

**Comment by sophia-guo** [comment]
Just a note that for jtreg 6+ we don't need to export build_number and build_version any more. Specification of version info was added in different version-numbers.txt files. When building use build.sh for jtreg6+ while buildall.sh for jtreg5. Though buildall.sh stays in the jtreg6+, which is confusing.
