### ISSUE TITLE
JDK17 pipelines are invoking build jobs with the wrong name

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#167]
Thank you for reporting a broken build! Please fill in the following details:

- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/128/console
- **Which platforms (OS+arch) are affected:** All
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a

Pipeline is trying to trigger jobs with `jdk17` in the name instead of `jdk` e.g.
```
 build name build-scripts/jobs/jdk17/jdk17-linux-aarch64-hotspot
```
when the underlying job is at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-aarch64-hotspot/

**Comment by gdams** [comment]
This is because the JDK18 tag landed yesterday. I'll fix this now
