### ISSUE TITLE
Java 17 nightly pipeline ran despite having disabled nightlies.

### ISSUE THREAD

**Issue by karianna** [adoptium/ci-jenkins-pipelines#189]
Hmm, for some reason the [Java 17 nightly pipeline](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/189/) still fired last night during the release.

Chances are the instructions for disabling the nightlies need to be updated?

**Comment by sxa** [comment]
It ran builds with no tests which is exactly what we have always agreed to do during this period. The builds are quick enough that they do not generally block release pipelines (whereas the tests would)
`enableTests: false` [is the change we make](https://github.com/adoptium/ci-jenkins-pipelines/pull/187/files). We do not inhibit the building of the nightlies completely
