### ISSUE TITLE
Set build pipelines fail and block the running of AQA tests if smoke tests fail

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#195]
Smoke Tests has been  incorporated into the Jenkins build pipelines. The outstanding failure in the smoke tests has been fixed. Looks like the tests has been stable. We'd like to suggest

- [x] set build pipeline jobs fail if failures occur in smoke tests jobs, which would be similar to installer jobs and sign installer jobs -https://github.com/adoptium/ci-jenkins-pipelines/issues/234

- [x] block the running of AQA tests if failures occur in smoke test jobs https://github.com/adoptium/ci-jenkins-pipelines/issues/121

For flexibility we can also add a flag so people can choose if blocking is preferred. Or Smoke tests will block the AQA tests and fail the build job for release. And it's non-blocker for other pipeline build(nightly). This way we can still run AQA tests for nightly builds and triage the tests at early stage even if smoke tests fail. However for release no AQA tests will run and build job should also fail if smoke tests. As smoke tests fail which means fatal issue,  and no other tests need to run and set a red flag for openjdk binaries.

**Comment by zdtsw** [comment]
duplicated as https://github.com/adoptium/ci-jenkins-pipelines/issues/121

**Comment by smlambert** [comment]
has this now been completed and can be closed?

**Comment by sophia-guo** [comment]
Close as part2  #121 is done.
