### ISSUE TITLE
Ensure we can use a particular branch of aqa-tests

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#207]
Test pipelines can take repo/branch information for various test repos, including aqa-tests (where the test definitions live).  We would like to use a particular branch for aqa-tests during a release to ensure stability and be able to continue development in the master branch (avoiding the need for a code freeze for AQAvit repositories).

This issue is to add the additional parameter into the parent build pipeline when test jobs are invoked.

**Comment by sophia-guo** [comment]
Based on the current aqa-tests jenkins jobs settings parameter ADOPTOPENJDK_BRANCH and USE_TESTENV_PROPERTIES need to be passed to test jobs.  

USE_TESTENV_PROPERTIES will need to be added in testJobTemplates. And all test jobs need to be regenerated manually. Alternatively we might need to add one more flag to force regenerate all test jobs automatically.

Currently the jdkbranch is set by `buildConfig.SCM_REF` for release and set by default branch per `buildConfig.VARIANT` for nightly or weekly. How will aqa-tests repo do the release so the JDK*_BRANCH property will be consistent with OpenJDK tag, e.g tag eg.jdk-11.0.4*?

As testenv.properties only have JDK*_REPO | BRANCH JDK*_OPENJ9_REPO|BRANCH does this mean we only enable this for VARIANT = hotspot and openj9? For others we will keep as before?
