### ISSUE TITLE
Build jtreg 6.1+1 for OpenJDK 18

### ISSUE THREAD

**Issue by jerboaa** [adoptium/ci-jenkins-pipelines#211]
Since yesterday OpenJDK 18 (current mainline development tree) requires `jtreg-6.1+1` due to removal of Security Manager. We should build that version of jtreg in addition to other versions for community consumption.

**Comment by sophia-guo** [comment]
@jerboaa Does that also mean for jdk18 we should use jtreg6.1+1 for tests? Thanks!
