### ISSUE TITLE
Update build matrix in README

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#215]
**What are you trying to do?**
Looking at the build matrix in the README, looks like it needs to be updated.  Lots of chiclets that are no longer populated with results (likely since changes in access to openj9 jobs has changed), also contains jdk15 and 16 which will no longer be valid, and should have columns for jdk17 (and java HEAD would be now jdk18).  If we are to keep this matrix, we should think about how it could be kept up-to-date without too much manual intervention.  The code is held in: [generateBuildMatrix.sh](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/docs/generateBuildMatrix.sh).

**Expected behaviour:**
Either to see build status, or to not see the chiclets in the matrix.

**Observed behaviour:**
https://github.com/adoptium/ci-jenkins-pipelines#build-status table contains a bunch of chiclets information which could be removed (or possibly made to be updated). 

**Any other comments:**

**Comment by zdtsw** [comment]
@smlambert could you assign this ticket to me? I will try update matrix and see if any better way to automatize this

**Comment by zdtsw** [comment]
Good to know "trss" dashboard!
Yeah, I am going thro the code to get some idea how everything is gluing together.

I will try to update this one first, 
in another thread/discussion to see if/which one(s) we can keep using and obsolete the others

**Comment by zdtsw** [comment]
created a new issue https://github.com/adoptium/ci-jenkins-pipelines/issues/282 which is related to how we use the script.

**Comment by zdtsw** [comment]
I guess to update READM.md , I need manually run generateBuildMatrix.sh + update README.md with output
