### ISSUE TITLE
Adoptium top level pipeline build should reflect all child job results

### ISSUE THREAD

**Issue by llxia** [adoptium/ci-jenkins-pipelines#234]
Currently, Adoptium top-level pipeline build (i.e., openjdk8-pipeline, openjdk11-pipeline, etc) does not reflect all child job results, especially not including AQA test build results. It causes confusing/misleading information. For example:

- If the top-level pipeline build is SUCCESS/green, it does not mean all AQA tests jobs are passed.
- If the top-level pipeline build is completed, it does not mean all AQA test jobs are completed. 

Adoptium top-level pipeline build should reflect all child job results so that the triage work can be easier. For example, if any AQA test build fails, the top-level pipeline build status should be FAILURE or UNSTABLE.

**Comment by smlambert** [comment]
related: https://github.com/adoptium/ci-jenkins-pipelines/issues/11

**Comment by karianna** [comment]
FYI - I think we'll need to provide the upgrade Jenkins to resolve this.

**Comment by smlambert** [comment]
As far as I am aware, this issue can be resolved by updating pipeline code and does not require a Jenkins upgrade to accomplish it.

**Comment by llxia** [comment]
Does anyone know why we have `propagate: false` for the test jobs?
https://github.com/adoptium/ci-jenkins-pipelines/blob/cee0b690b2a3a199b1f3f77892b6a1e18a20ea3b/pipelines/build/common/openjdk_build_pipeline.groovy#L292

**Comment by smlambert** [comment]
The only reason was historically, we did not have many clean runs.  Now that we have cleaned up the test jobs (a lot), we should be switching that to true.  That may be sufficient to resolve this issue (to have top-level pipeline build reflect test job status at least).  Other child jobs like smoke tests and installers would need their own adjustments.

**Comment by andrew-m-leonard** [comment]
I think the following would need updating:
- Smoketest propagate set to true
- AqaTests popagate set to true
- The pipeline templates need propagateFailures defaulting to true
   - https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/pipeline_job_template.groovy
   - https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/release_pipeline_job_template.groovy

**Comment by smlambert** [comment]
Related: #121 #195

**Comment by smlambert** [comment]
@chandrashritii - can you add a comment to this issue, so we can add you as an assignee?

**Comment by chandrashritii** [comment]
> @chandrashritii - can you add a comment to this issue, so we can add you as an assignee?

Sure @smlambert I'd love to take this up. Could you please assign the issue to me?
