### ISSUE TITLE
Pipeline failure trying to build 11.0.14.1+1

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#237]
Thank you for reporting a broken build! Please fill in the following details:

- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-hotspot/1002/console
- **Which platforms (OS+arch) are affected:** Probably all
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No, but irrelevant
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a

The new 11.0.11.1+9 builds are failing to build with the following error after the builds have completed but before the tests are initiated:

```
16:11:52  Execution error: hudson.AbortException: script returned exit code 1
```

**Comment by sxa** [comment]
As you were - I'd cut & pasted and extra space into the end of the `SCM_REF` value

**Comment by smlambert** [comment]
Can update the Jenkins param to trim whitespace?

**Comment by sxa** [comment]
> Can update the Jenkins param to trim whitespace?

That would be the ideal thing to do - it's not the first time I've cut & pasted with an erroneous space ;-)

**Comment by sxa** [comment]
Closing as I've raised https://github.com/adoptium/ci-jenkins-pipelines/issues/238
