### ISSUE TITLE
Add Build and Test Labels as a parameter to the build pipelines

### ISSUE THREAD

**Issue by lumpfish** [adoptium/ci-jenkins-pipelines#24]
There is currently no way to tell a pipeline which node to run tests on.

There are tests which fail only on certain machines.  Having this capability would provide the means to check whether a particular machine is actually capable of running any test which might land on it (e.g. following the addition of a new machine or reconfiguration of an existing one) or to find exactly which tests are affected by an incorrect configuration

It might also be useful to be able to specify which machine to run the build part of the pipeline on.

**Comment by M-Davies** [comment]
@lumpfish Does this not already exist as [additionalTestLabels](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines#data-fields)?

**Comment by AdamBrousseau** [comment]
I think what Simon is looking for is a build time parameter that can be set to target a specific machine as a 1-off both for the compile and the test(s). One might argue that you could simply use the grinder for the test side but a counter argument would be for a new machine that is build & test capable you could target the single machine for both parts of the build in one shot.

**Comment by aahlenst** [comment]
Letting the user target machines has security implications. It has to be done in such a way that the CI system must ignore those requests when they are invalid, for example when a build should happen on a non-build machine (we could special-case throwaway builds) or a test on a non-test system.

**Comment by lumpfish** [comment]
It looks like what I'm looking for does actually exist.  The first jobs started by the pipeline - e.g. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-openj9/952/parameters/ allows the user to specify 'NODE_LABEL' which I assume is then passed down to all sub-jobs.

**Comment by lumpfish** [comment]
Closing on the basis of comment https://github.com/adoptium/ci-jenkins-pipelines/issues/24#issuecomment-818209865
