### ISSUE TITLE
Test job failed with `DETECTED_JDK_IMPL value is hotspot, settled JDK_IMPL value is temurin`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#244]
Related with https://github.com/adoptium/ci-jenkins-pipelines/pull/226

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-64_mac/211/console

**Comment by sophia-guo** [comment]
[if (jdk_Version == "temurin") ](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L184) should be `buildConfig.VARIANT`

**Comment by smlambert** [comment]
There is code within TKG that may also be affected and need to be updated, https://github.com/adoptium/TKG/blob/master/src/org/openj9/envInfo/JavaInfo.java#L131.
