### ISSUE TITLE
Smoke tests are getting JDK_IMPL=temurin unlike other jobs

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#250]
**What are you trying to do?** Run smoke test jobs successfully in the nightly pipelines

**Expected behaviour:** Builds success 

**Observed behaviour:** Builds fail as theyt are being passed `JDK_IMPL=temurin` instead of the other test jobs which are getting `JDK_IMPL=hotspot` - basically the smoke tests do not seem to be subject to https://github.com/adoptium/ci-jenkins-pipelines/blob/31ad2d4c3e1c0bf8acb3a067bc9a408c0edc1ee9/pipelines/build/common/openjdk_build_pipeline.groovy#L184, which is odd since that code is in `getCommonTestJobParams` which is called from [getSmokeTestJobParams](https://github.com/adoptium/ci-jenkins-pipelines/blob/31ad2d4c3e1c0bf8acb3a067bc9a408c0edc1ee9/pipelines/build/common/openjdk_build_pipeline.groovy#L142) and [getAQATestJobParams](https://github.com/adoptium/ci-jenkins-pipelines/blob/31ad2d4c3e1c0bf8acb3a067bc9a408c0edc1ee9/pipelines/build/common/openjdk_build_pipeline.groovy#L162)

**Any other comments:**

**Comment by sxa** [comment]
@sophia-guo Is there anything special about the way the smoke test jobs are assembled that means they are missing this parameter adjustment from `temurin` to `hotspot`?

**Comment by sxa** [comment]
OK I'm now even more confused by what's happening ...

If I run https://ci.adoptopenjdk.net/view/work-in-progress/job/SXA-LinuxARMbuildTest/, which is a straight copy of https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin/, it passed `JVM_IMPL=hotspot` into the [generated smoke test job which passed](https://ci.adoptopenjdk.net/job/SXA-LinuxARMbuildTest_SmokeTests/1/console), but it doesn't for the [smoke test on the original pipeline](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin_SmokeTests/7/)

@sophia-guo Any idea why this is happening?

**Comment by sophia-guo** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/blob/31ad2d4c3e1c0bf8acb3a067bc9a408c0edc1ee9/pipelines/build/common/openjdk_build_pipeline.groovy#L184 is in PR https://github.com/adoptium/ci-jenkins-pipelines/pull/245, which is to fix this. The failed smoke tests were generated before this fix and need to be regenerated.

**Comment by sophia-guo** [comment]
Note, recent AQA_AUTO_GEN only work for aqa test jobs, which doesn't work for smoke test job.

**Comment by sxa** [comment]
> https://github.com/adoptium/ci-jenkins-pipelines/blob/31ad2d4c3e1c0bf8acb3a067bc9a408c0edc1ee9/pipelines/build/common/openjdk_build_pipeline.groovy#L184
> is in PR #245, which is to fix this. The failed smoke tests were generated before this fix and need to be regenerated.

Hmmm OK I'm a bit confused as to how this works then as I thought that code was in the pipeline code that sets the parameters that are used to call the smoke test job - I'd run the regeneration of the build pipeline so thought that would change the input to the smoke test job, but I'll try deleting the smoke test job and retrying ...

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin/8/console

**Comment by sxa** [comment]
LGTM - I'll delete all the `temurin_SmokeTest` jobs and let them be regenerated. Backup created as temurin_SmokeTests.tar.xz in the jobs directory on the jenkins master.

**Comment by sxa** [comment]
Now working.
