### ISSUE TITLE
nightlyBuildAndTestStats jobs are not running successfully

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#254]
**What are you trying to do?** Look at the following jobs, and see their output in the #build slack channel:
- https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot
- https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_openj9
- https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_dragonwell
- https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_bisheng

**Expected behaviour:** Reports are published to slack

**Observed behaviour:** No reports are published to slack, jobs have been failing since February 16th

**Any other comments:** May coincide with the [`hotspot` -> `temurin` switchover](https://github.com/adoptium/ci-jenkins-pipelines/pull/226) which was merged on February 15th.

NOTE: This has also highlighted that we'll probably want to replace "hotspot" with "temurin" in the above job list (or keep both for when https://github.com/adoptium/ci-jenkins-pipelines/pull/251 is approved and merged)

**Comment by andrew-m-leonard** [comment]
Seems to be a connection issue to TRSS API, trying manually:
```
wget https://trss.adoptopenjdk.net/api/getBuildHistory?buildName=openjdk11-pipeline
--2022-02-28 13:19:35--  https://trss.adoptopenjdk.net/api/getBuildHistory?buildName=openjdk11-pipeline
Resolving trss.adoptopenjdk.net (trss.adoptopenjdk.net)... 104.17.158.60, 104.17.159.60, 2606:4700::6811:9f3c, ...
Connecting to trss.adoptopenjdk.net (trss.adoptopenjdk.net)|104.17.158.60|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://trss.adoptium.net/api/getBuildHistory?buildName=openjdk11-pipeline [following]
--2022-02-28 13:19:35--  https://trss.adoptium.net/api/getBuildHistory?buildName=openjdk11-pipeline
Resolving trss.adoptium.net (trss.adoptium.net)... 54.78.186.5
Connecting to trss.adoptium.net (trss.adoptium.net)|54.78.186.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 254986 (249K) [application/json]
Saving to: ‘getBuildHistory?buildName=openjdk11-pipeline.1’

getBuildHistory?buildName=openjdk  51%[==============================>                               ] 127.70K  --.-KB/s    in 0.05s   

2022-02-28 13:19:35 (2.50 MB/s) - Connection closed at byte 130767. Retrying.
```

**Comment by andrew-m-leonard** [comment]
Seems to truncate at 127k

**Comment by andrew-m-leonard** [comment]
Problem was due to space issues on the TRSS server, causing truncated http reponses.
