### ISSUE TITLE
SDK_RESOURCE needs to be set in the pipeline

### ISSUE THREAD

**Issue by llxia** [adoptium/ci-jenkins-pipelines#256]
Currently, we do not set SDK_RESOURCE in the upstream pipeline and we depend on the test pipeline default values. We should set SDK_RESOURCE explicitly in the pipeline.

- Add SDK_RESOURCE=upstream
https://github.com/adoptium/ci-jenkins-pipelines/blob/cee0b690b2a3a199b1f3f77892b6a1e18a20ea3b/pipelines/build/common/openjdk_build_pipeline.groovy#L295

**Comment by YeeSkywalker** [comment]
Hi there, I am wondering if I could take this one? It would be much appreciated!

**Comment by smlambert** [comment]
Go for it @YeeSkywalker !
