### ISSUE TITLE
Enable weekly sanity.external testing on other versions besides jdk11

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#273]
We enabled weekly testing for jdk11 xlinux via https://github.com/adoptium/ci-jenkins-pipelines/pull/263, and now wish to extend the testing to jdk8/jdk17+ for that top-level target.

**Comment by zdtsw** [comment]
related to issue https://github.com/adoptium/ci-jenkins-pipelines/issues/219

**Comment by zdtsw** [comment]
unassigned myself on this issue.
Can check if we are ready to merge PR #412

**Comment by smlambert** [comment]
This issue is encompassed by #857 (close as dup)
