### ISSUE TITLE
Remove missleading "Created job.." msg

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#276]
The pipelines/build/common/build_base_file.groovy issues a "Created job.." message when starting a build, but it 
hasn't actually created the job, that logic was removed a long time ago when concurrent pipelines support was added.

Remove the msg: https://github.com/adoptium/ci-jenkins-pipelines/blob/5edf557be5ce1598ea764fa6a985126d67621877/pipelines/build/common/build_base_file.groovy#L769

If possible add a check of the downstreamJobName existance, and issue need to re-gen message...

**Comment by zdtsw** [comment]
I assume the error is in job e.g https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull
`(https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull#)[](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull#)[](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull#)[](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull#)[](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull#)[](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/342/consoleFull#)[Pipeline]
{ (windows-x64-temurin)
[Pipeline] echo
14:05:24  Created job build-scripts/jobs/jdk17u/jdk17u-linux-aarch64-temurin
[Pipeline] echo
14:05:24  Created job build-scripts/jobs/jdk17u/jdk17u-mac-aarch64-temurin
[Pipeline] echo
14:05:24  Created job build-scripts/jobs/jdk17u/jdk17u-linux-arm-temurin
[Pipeline] echo
14:05:24  Created job build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin
[Pipeline] echo
14:05:24  Created job build-scripts/jobs/jdk17u/jdk17u-linux-ppc64le-temurin`
