### ISSUE TITLE
Nightly build rating Slack msg "Detail" html link points at old build

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#278]
Current Detail link points at: https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_temurin/632/console
But latest is: https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_temurin/642/

**Comment by zdtsw** [comment]
I think the problem is: every 12:15 (CET) and 14:15(CET) it posts twice to Slack build channel. First one at 12:15 with correct info/jenkins job link(build nr. N) , but the second one at 14:15 points back to old links (build nr. N-1).

**Comment by zdtsw** [comment]
i did a quick check, could not find any job in https://ci.adoptopenjdk.net/ made a run around 14:15 :confused:

**Comment by andrew-m-leonard** [comment]
> I think the problem is: every 12:15 (CET) and 14:15(CET) it posts twice to Slack build channel. First one at 12:15 with correct info/jenkins job link(build nr. N) , but the second one at 14:15 points back to old links (build nr. N-1).

@zdtsw good spot I hadn't noticed that, interesting

**Comment by sxa** [comment]
Looks like this was probably from the backup server I was testing before we did the OS upgrade on the main one. I've shut that down now. Apologies for the confusion - I should have realised that's where it could have been coming from.
