### ISSUE TITLE
Release sign_installer jobs should stay around for longer

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/ci-jenkins-pipelines#302]
A request/discussion for the [sign_installer](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_installer/) jobs to stay 'locked' for releases.

This was an issue during the recent April release, where a x64 MacOS release build failed at the sign_installer stage. However I was not able to view the log as the job had already vanished after a nightlies run.

The artefacts of the build pipelines remain 'locked' during a release, perhaps the same can be applied to the sign_installer job (or another stage of the release pipeline)

**Comment by adamfarley** [comment]
I agree with this, and I also recommend that we need to keep the job output from *all* sign_installer jobs for more than 48hrs. Anything we run on Friday evening is gone by the time Monday rolls around, which makes triage impossible. 

Currently, we seem to hold on to about 2 days of results, so can we double whatever the current limit is, please? If space is a concern, one option could be to leave the limit on file retention as it is, and only increase the number of days/runs that we keep the job output text.

**Comment by sxa** [comment]
Space for logs isn't a concern for this job. I've adjusted it so that it keeps 30 days worth of builds, which should be more than adequate for debugging important failures :-)
