### ISSUE TITLE
pipelines/library functions don't always load

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#345]
```
+ cd pipelines/library
+ git init
Reinitialized existing Git repository in /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-mac-x64-temurin/pipelines/library/.git/
+ git add --all .
+ git config user.email none
+ git config user.name none
+ git commit -m init
On branch master
nothing to commit, working tree clean
[Pipeline] sh
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2b1fd3e51da1df4db8569a255780d0685a8780cf # timeout=10
+ pwd
[Pipeline] library
Loading library local-lib@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.35.1'
 > git ls-remote -- /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-mac-x64-temurin/pipelines/library # timeout=10
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git ls-remote -- /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-mac-x64-temurin/pipelines/library" returned status code 128:
stdout: 
stderr: fatal: '/home/jenkins/.jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk18u/jdk18u-mac-x64-temurin/pipelines/library' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2096)
```

The functions are loaded in this rather odd way:
https://github.com/adoptium/ci-jenkins-pipelines/blob/3ce38164e391ec211b0c8340af0b4575a85961d6/pipelines/build/common/import_lib.groovy

We should instead integrate these ci-jenkins-pipelines groovy library functions (https://github.com/adoptium/ci-jenkins-pipelines/tree/master/pipelines/library/src) into our proper Jenkins managed helper here: https://github.com/adoptium/jenkins-helper/tree/master/src

**Comment by zdtsw** [comment]
I can only think of the reason why our build system has two different shared-library is:
the _jenkins-helper_ git repo captures all generate functions of operation to jenkins controller. so anyone can clone and use it in their jenkins settings.
code in _ci-jenkins-pipeline/pipelins/libary/src_ are specific logic to openjdk and temurin-build scripts.

since we need both , we have 2 loader
library(identifier: 'openjdk-jenkins-helper@master')
library(identifier: 'local-lib@master')

**Comment by zdtsw** [comment]
> I can only think of the reason why our build system has two different shared-library is: the _jenkins-helper_ git repo captures all generate functions of operation to jenkins controller. so anyone can clone and use it in their jenkins settings. code in _ci-jenkins-pipeline/pipelins/libary/src_ are specific logic to openjdk and temurin-build scripts.
> 
> since we need both , we have 2 loader library(identifier: 'openjdk-jenkins-helper@master') library(identifier: 'local-lib@master')

I take it back. 
we do have tight check to api, jenkins controller in _jenkins-helper_ repo , so it should be open to import these code from ci-jenkins-pipeline to it

**Comment by andrew-m-leonard** [comment]
We could just move the code as well..

**Comment by zdtsw** [comment]
yeah, the easiest way is to move all these code 
just need to think about how these testcases will be run

**Comment by smlambert** [comment]
Remembering the main consideration when refactoring is "who is using the code" and "how will they be affected".

**Comment by smlambert** [comment]
Yes, I am just noting that AQAvit pipelines also use jenkins-helper, not just build pipelines (and while I know you are not yet proposing changing things so much that the current API is changed).

**Comment by andrew-m-leonard** [comment]
Yeah, i'm in the middle as to whether it's the right place to put them.. the jenkins-helper is basically Jenkins node/machine helper functions... these are specific helper functions for the ci-jenkins-pipelines scripts.

@zdtsw we should try the simple fix to start with and ensure the library/src folder contains no pre-existing .git repo (that maybe corrupt or...), ie.a rm here: https://github.com/adoptium/ci-jenkins-pipelines/blob/3ce38164e391ec211b0c8340af0b4575a85961d6/pipelines/build/common/import_lib.groovy#L21

**Comment by andrew-m-leonard** [comment]
Maybe, needs investigating, this is the code in question: https://github.com/adoptium/ci-jenkins-pipelines/blob/d6e5fb6f76b3f29431d1a92b198a0a5c1ba68b33/pipelines/build/common/kick_off_build.groovy#L39

**Comment by andrew-m-leonard** [comment]
> isnit it easier to have a cleanWs() in the beginning for the job? unless build time will be much longer because everything is cleaned up.

The build jobs do cache the workspace clone so cleaning the whole job would impact build time...
I'd recommend just the pipelines/library git repo it creates

**Comment by AdamBrousseau** [comment]
>@AdamBrousseau I presume your Jenkins defines the openjdk-jenkins-helper for https://github.com/adoptium/jenkins-helper ?

Yes
