### ISSUE TITLE
Incorporate triggerRemoteJob of jck tests for weekly/release pipeline runs on remote Jenkins server

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#384]
Just as we trigger smoke tests and AQAvit tests from the build pipelines, we will trigger jck tests (on the private ci.eclipse.org/temurin-compliance server) for the weekly and release pipelines.

We have the parameterized-remote-trigger-plugin installed on ci.adoptopenjdk.net (see https://github.com/jenkinsci/parameterized-remote-trigger-plugin/blob/master/README_PipelineConfiguration.md for details of usage).  There may need to be some Jenkins configuration as well (including credentials) that go along with this new feature.

As the test jobs are named following a [particular naming convention](https://github.com/adoptium/aqa-tests/wiki/Naming-Convention-for-Test-Builds-in-Jenkins) on both Jenkins servers, we should be able to follow the same pattern for job names.  Given the limited number of machines available in the temurin-compliance project, we will like to run sanity.jck and special.jck jobs with PARALLEL=None, and extended.jck with PARALLEL=Dynamic, NUM_MACHINES=2 for most platforms.  There are likely a couple exceptions to this, but it can be tweaked later.

**Comment by zdtsw** [comment]
the difficulties of using this plugin:
- to get the token/credential for the remote server(i.e ci.eclipse.org/temurin-compliance) with build permission. this need get EF involved and generate that for us.
- to have a secured way store this information and config it on our server(i.e ci.adoptopenjdk.net).e.g config.xml of jenkins or by Jcasc

**Comment by smlambert** [comment]
Related: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1673

Note this one is already assigned to @sophia-guo

**Comment by sophia-guo** [comment]
For temporary trying and testing we will need to add the my personal eclispe-temurin API token in adoptium jenkins.

**Comment by zdtsw** [comment]
https://issues.jenkins.io/browse/JENKINS-68898
a bug in this plugin (i assume we are using 3.1.6.1 in our public jenkins server) so we cannot use multiple parameters

**Comment by karianna** [comment]
> https://issues.jenkins.io/browse/JENKINS-68898

Correct we're waiting for an upstream fix

**Comment by sophia-guo** [comment]
https://issues.jenkins.io/browse/JENKINS-68898 is talking about multiple lines parameters, which has been documented well. There is not issue with 'multiple parameters' https://github.com/adoptium/ci-jenkins-pipelines/issues/384#issuecomment-1242155047.



> Job Parameters
> Parameters which will be used when triggering the remote job.
> If no parameters are needed, then just leave this blank.
> In case of a String, the plugin uses String/File parameters depending on the parameter's content.
> Map parameters
> Map<String, Object>
> 
> This is the recommended type. It allows you to provide parameters with key/value and supports multi-line parameters.
> 
> String parameters (legacy)
> String
> 
> This type allows to describe parameters within a big string like in versions 3.1.5 and lower. It does not support multi-line parameters.
> 
> File parameters (legacy)
> String
> 
> **This type allows to describe parameters within a file like in versions 3.1.5 and lower. It does not support multi-line parameters.**
