### ISSUE TITLE
Grinder should use the same parameter value from upstream job

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#392]
**Describe the bug**
Trying to run grinder from test job, but grinder trying to download "nightly" jdk from API VS original upstream job is copying jdk from build artifact
This could give the false test result if jdk is not the one from last build. 
Since we have some problems to download the latest ones from jdk19/20 therefor grinder failed, 
But for other jdk versions, grinder wont failed to download jdk so the test result might not be accurate.  

**To Reproduce**
original upstream job https://ci.adoptopenjdk.net/job/Test_openjdk20_hs_sanity.functional_x86-64_alpine-linux/11/consoleFull
click link from console to run grinder https://ci.adoptopenjdk.net/job/Grinder/5564/console

**Expected behavior**
grinder pre-fill value 
![Screenshot from 2022-09-01 07-53-29](https://user-images.githubusercontent.com/915053/187841599-313626db-4183-498a-8600-4833f332f3a2.png)
because in original upstream job it does not set SDK_RESOURCE, then grinder fall back to the first item from dropdownlist "nightly"

**Screenshots**
![Screenshot from 2022-09-01 07-54-46](https://user-images.githubusercontent.com/915053/187841741-23eaad0e-bf01-4958-a814-7673e666c965.png)

both jobs set correct upstream job information
![Screenshot from 2022-09-01 07-56-04](https://user-images.githubusercontent.com/915053/187841970-cfd0c833-8165-4ba7-8d20-50af5dfe898f.png)

**Comment by sophia-guo** [comment]
It is upstream in the template. https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L46.

It is the way how the Test_Job_Auto_Gen is configured. @llxia any concern if we set sdk_resource to be upstream by default in the job https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/configure?

**Comment by smlambert** [comment]
I have changed the Test_Job_Auto_Gen SDK_RESOURCE to default to upstream.

**Comment by llxia** [comment]
Yes, it is ok to set SDK_RESOURCE to default to upstream in Test_Job_Auto_Gen. The correct way is to set the value in the pipeline. @sophia-guo you have already figured it out - https://github.com/adoptium/ci-jenkins-pipelines/pull/391.
