### ISSUE TITLE
Nightly build stats build is not working on jdk8

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#406]
**What are you trying to do?**
we do have build 2 days ago, but the result saying jdk8 last published 7 days ago
this is because we made an EA build for jdk8 and API sort it by name which became the first element to return https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/nightly_build_and_test_stats.groovy#L50

so jdk8u352-b05-ea will be used all the time for jdk8 nightly build status which is incorrect.

**Expected behaviour:**
Get correct status from job https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_temurin/804/console
```
[
    {
        "binaries": [
            {
                "architecture": "x64",
                "download_count": 395,
                "heap_size": "normal",
                "image_type": "jdk",
                "jvm_impl": "hotspot",
                "os": "linux",
                "package": {
                    "checksum": "2bf66c3e1c010b7df3ecfde53f4d280fb6352d0617393e4711756f3326d9a1de",
                    "checksum_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b05-ea/OpenJDK8U-jdk_x64_linux_hotspot_8u352b05_ea.tar.gz.sha256.txt",
                    "download_count": 395,
                    "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b05-ea/OpenJDK8U-jdk_x64_linux_hotspot_8u352b05_ea.tar.gz",
                    "metadata_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b05-ea/OpenJDK8U-jdk_x64_linux_hotspot_8u352b05_ea.tar.gz.json",
                    "name": "OpenJDK8U-jdk_x64_linux_hotspot_8u352b05_ea.tar.gz",
                    "signature_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b05-ea/OpenJDK8U-jdk_x64_linux_hotspot_8u352b05_ea.tar.gz.sig",
                    "size": 102936760
                },
                "project": "jdk",
                "scm_ref": "jdk8u352-b05_adopt",
                "updated_at": "2022-09-05T18:43:31Z"
            }
        ],
        "download_count": 6374,
        "id": "RE_kwDOFjpgDM4EjHkm.7R859jy0sVmsrw==",
        "release_link": "https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u352-b05-ea",
        "release_name": "jdk8u352-b05-ea",
        "release_type": "ea",
        "source": {
            "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b05-ea/OpenJDK8U-jdk-sources_8u352b05_ea.tar.gz",
            "name": "OpenJDK8U-jdk-sources_8u352b05_ea.tar.gz",
            "size": 88330194
        },
        "timestamp": "2022-09-05T18:35:24Z",
        "updated_at": "2022-09-07T22:04:26Z",
        "vendor": "eclipse",
        "version_data": {
            "build": 5,
            "major": 8,
            "minor": 0,
            "openjdk_version": "1.8.0_352-beta-ea-b05",
            "pre": "ea",
            "security": 352,
            "semver": "8.0.352-ea+5"
        }
    },
    {
        "binaries": [
            {
                "architecture": "x64",
                "download_count": 3,
                "heap_size": "normal",
                "image_type": "jdk",
                "jvm_impl": "hotspot",
                "os": "linux",
                "package": {
                    "checksum": "29bb703a26da3de20a77ff88df6bac867c391e683249f61d382a557ce36eccf6",
                    "checksum_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz.sha256.txt",
                    "download_count": 3,
                    "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz",
                    "metadata_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz.json",
                    "name": "OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz",
                    "signature_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz.sig",
                    "size": 102948722
                },
                "project": "jdk",
                "scm_ref": "jdk8u352-b05_adopt-50-gbb4f7da37a",
                "updated_at": "2022-09-13T06:01:03Z"
            }
        ],
        "download_count": 237,
        "id": "RE_kwDOFjpgDM4ElmDp.L1IIPDtOlTvQNA==",
        "release_link": "https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u-2022-09-13-05-46-beta",
        "release_name": "jdk8u-2022-09-13-05-46-beta",
        "release_type": "ea",
        "source": {
            "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk-sources_2022-09-12-18-05.tar.gz",
            "name": "OpenJDK8U-jdk-sources_2022-09-12-18-05.tar.gz",
            "size": 88333059
        },
        "timestamp": "2022-09-13T05:57:55Z",
        "updated_at": "2022-09-13T06:03:20Z",
        "vendor": "eclipse",
        "version_data": {
            "build": 5,
            "major": 8,
            "minor": 0,
            "openjdk_version": "1.8.0_352-beta-202209121816-b05",
            "optional": "202209121816",
            "pre": "beta",
            "security": 352,
            "semver": "8.0.352-beta+5.0.202209121816"
        }
    },
...
```

**Observed behaviour:**
```-------------- Nightly pipeline health report ------------------
[Pipeline] echo
===> JDK 8 nightly pipeline publish status: unhealthy. Last published: 7 day(s) ago. Stale threshold: 5 days.
```

**Any other comments:**
maybe it is good to just add `page_size=1` in query, so we only get 1 return which is much less data load for parsetext.

**Comment by zdtsw** [comment]
not really sure if we do need `jdk8u352-b05-ea` set to release_type="ea"
or maybe we should have another value e.g "other" so any build not belong to ga or nightly, should be the others?

if we do not want to change anything in the API part, (e.g remove that record or set it ea to something else for jdk8u352-b05-ea, then we need to hardcode our build to skip jdk8u352-b05-ea. =>  `def ts = assetsJson[1].timestamp // newest timestamp of a jdk asset`

**Comment by jerboaa** [comment]
Tagging on `&sort_order=DESC&sort_method=DATE` to the API call should be sufficient to fix it.

**Comment by jerboaa** [comment]
also add `&pages=1` as you've suggested while you're at it ;-)

**Comment by zdtsw** [comment]
> Tagging on `&sort_order=DESC&sort_method=DATE` to the API call should be sufficient to fix it.
> 
> ```
> $ curl 'https://api.adoptium.net/v3/assets/feature_releases/8/ea?image_type=jdk&os=linux&architecture=x64&jvm_impl=hotspot&sort_order=DESC&sort_method=DATE' | jq '.[0]'
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 25123    0 25123    0     0  40013      0 --:--:-- --:--:-- --:--:-- 40004
> {
>   "binaries": [
>     {
>       "architecture": "x64",
>       "download_count": 3,
>       "heap_size": "normal",
>       "image_type": "jdk",
>       "jvm_impl": "hotspot",
>       "os": "linux",
>       "package": {
>         "checksum": "29bb703a26da3de20a77ff88df6bac867c391e683249f61d382a557ce36eccf6",
>         "checksum_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz.sha256.txt",
>         "download_count": 3,
>         "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz",
>         "metadata_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz.json",
>         "name": "OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz",
>         "signature_link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk_x64_linux_hotspot_2022-09-13-05-46.tar.gz.sig",
>         "size": 102948722
>       },
>       "project": "jdk",
>       "scm_ref": "jdk8u352-b05_adopt-50-gbb4f7da37a",
>       "updated_at": "2022-09-13T06:01:03Z"
>     }
>   ],
>   "download_count": 237,
>   "id": "RE_kwDOFjpgDM4ElmDp.L1IIPDtOlTvQNA==",
>   "release_link": "https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u-2022-09-13-05-46-beta",
>   "release_name": "jdk8u-2022-09-13-05-46-beta",
>   "release_type": "ea",
>   "source": {
>     "link": "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u-2022-09-13-05-46-beta/OpenJDK8U-jdk-sources_2022-09-12-18-05.tar.gz",
>     "name": "OpenJDK8U-jdk-sources_2022-09-12-18-05.tar.gz",
>     "size": 88333059
>   },
>   "timestamp": "2022-09-13T05:57:55Z",
>   "updated_at": "2022-09-13T06:03:20Z",
>   "vendor": "eclipse",
>   "version_data": {
>     "build": 5,
>     "major": 8,
>     "minor": 0,
>     "openjdk_version": "1.8.0_352-beta-202209121816-b05",
>     "optional": "202209121816",
>     "pre": "beta",
>     "security": 352,
>     "semver": "8.0.352-beta+5.0.202209121816"
>   }
> }
> ```

ahhhhhhhh, how could i missed that one
