### ISSUE TITLE
Remote trigger to Temurin Compliance server should not occur when nightly testing is disabled

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#422]
**Expected behaviour:** Weekly runs, which have testing disabled, should not initiate the TC trigger

**Observed behaviour:** Weekly jobs are running the TC trigger during lockdown

**Any other comments:** The logs currently don't show when the trigger is being executed in the logs - ideally we should add this in since it's currently happening silently which made this harder to look into
Sample log from the [Windows weekly run which didn't run the AQA tests](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/116/) but the [pipeline job did trigger TC](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2094/console):  - it launched https://ci.eclipse.org/temurin-compliance/job/AQA_Test_Pipeline/94

Ref: functionality introduced in https://github.com/adoptium/ci-jenkins-pipelines/commit/b5ffce4bdb5c6c2702e9639c3a559a65d418ffd7

FYI @smlambert as discussed recently
FYI @sophia-guo

**Comment by sophia-guo** [comment]
This also suggests weekly-openjdk*-pipeline should be disabled if testing is disabled? My understanding is the weekly openjdk pipeline is mainly to run full set of defined tests( nightly + weekly) by running the openjdk build pipeline first. If testing is disabled should those pipelines be disabled? That means the openjdk build pipeline will not be triggered too. Currently those pipelines are triggered by timer and run the openjdk build pipeline.

**Comment by sophia-guo** [comment]
Thanks @sxa @andrew-m-leonard for confirming that weekly openjdk pipelines are also regular openjdk builds for all different vendors. For non-temurin ones they are only running weekly so even if testing is disabled we'd still like to keep the pipeline running to build jdk. 

In that case would it be helpful to disable weekly temurin build if testing is disabled?
