### ISSUE TITLE
Error: GH action super-linter failed on groovy linter with warnings not real error

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#425]
GH action linter check start to fail during this weekend. 

Have not identify if it is a change made recently in codenarc or the npm-groovy-lint or by  super-linter
which does more changes than before.
so the file not been touched start to show up warnings

and the result seems not only count "error" but also "warnings" so we get failed GH action runs

e.g

```
2022-10-03 02:24:59 [INFO]   File:[/github/workspace/pipelines/build/common/build_base_file.groovy]
2022-10-03 02:25:11 [ERROR]   Found errors in [npm-groovy-lint] linter!
2022-10-03 02:25:11 [ERROR]   Error code: 1. Command output:
....
npm-groovy-lint results in 1 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │     60      │
│    2    │  'Info'   │     197     │
└─────────┴───────────┴─────────────┘
Failure: 0 error(s) have been found 
 60 warning(s) have been found

2022-10-03 02:25:14 [ERROR]   ERRORS FOUND in GROOVY:[1]

```

**Comment by zdtsw** [comment]
should have "https://github.com/nvuillam/npm-groovy-lint" to set` --failon error `so we can ignore warning. 
unless we decide to fix all warning

**Comment by zdtsw** [comment]
report issue in https://github.com/github/super-linter/issues/3391

**Comment by zdtsw** [comment]
For tractability:
so to summarize a bit for what happened for the linter incident (follow the timeline):

- 10 months ago super-linter enabled "--failon warning" by default for all groovy checks, 

- on 25th July super-linter released v4.9.5 and a new docker image ghcr.io/github/super-linter:v4.9.5 

- on 2nd Aug super-linter release a new docker image ghcr.io/github/super-linter:v4.9.6 (https://github.com/github/super-linter/actions/runs/2783363071) `ghcr.io/github/super-linter:v4.9.6@sha256:65320e0da6fc983fccdca70cb74cb30bc55797300384ecc82458b42bb8d30828` not really sure if this is a mistake or a different release process?

- on 9 Agu: our GH action started to use v4.9.6 image (SHA1: 65320e0da6fc983fccdca70cb74cb30bc55797300384ecc82458b42bb8d30828)

- on 15th Aug: npm-groovy-lint add the support for more codenarc rules and also update megalint for the release v10.0.0

- on 30th Sep: super-linter released v4.9.6 which bumped version of npm-groovy-lint to v10.0.0 also made another v4.9.6 image (https://github.com/github/super-linter/actions/runs/3161263459/jobs/5146653515) as `ghcr.io/github/super-linter:v4.9.6: digest: sha256:251e96e712bb704493e15f1598c0461098445b6eec7454d8bd75bad79e82e93a `

- on 2nd Oct: we start to see failure on our GH action checks even we use the same v4.9.6 of super-lint but SHA1 has been changed from `65320e0da6fc983fccdca70cb74cb30bc55797300384ecc82458b42bb8d30828`  to `251e96e712bb704493e15f1598c0461098445b6eec7454d8bd75bad79e82e93a`

**Comment by sophia-guo** [comment]
My PR linter job got similar output but failed and reported one error. https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/3177396948/jobs/5177786644 . Is that the same issue?

**Comment by andrew-m-leonard** [comment]
I don't errors now, I think we've fixed all these?
