### ISSUE TITLE
openjdk pipeline not working, with error "failed to write new configuration file /home/jenkins/.jenkins/workspace/build-scripts/openjdk17-pipeline/.git/config.lock"

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#426]
Thank you for reporting a broken build! Please fill in the following details:

- **Jenkins link to the failing log:**
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/514/console
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/504/console  
thread: https://adoptium.slack.com/archives/C09NW3L2J/p1664779332872109

- **Which platforms (OS+arch) are affected:** All
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No

**Comment by sxa** [comment]
This is due to an out of space condition. Since we are running multiple copies of `openjdkXX-pipeline` at the weekend there is a new `openjdkXX-pipeline@X` directory created for each. This uses up additional space over what is expected.

It looks like the `weekly-openjdkXX-pipeline` jobs also store copies of the tarballs in the server worksapce in addition to the individial pipeline jobs causing duplication and extra space use e.g.

```
root@c3-awx:/home/jenkins/.jenkins/workspace/build-scripts# find . -name OpenJDK8U-jdk_aarch64_alpine-linux_hotspot_2022-10-01-12-06.tar.gz -ls
  7871968  98136 -rw-r--r--   1 jenkins  ciagent  100487981 Oct  1 12:17 ./weekly-openjdk8-pipeline/workspace/OpenJDK8U-jdk_aarch64_alpine-linux_hotspot_2022-10-01-12-06.tar.gz
  7089526  98136 -rw-r--r--   1 jenkins  ciagent  100487981 Oct  1 12:17 ./openjdk8-pipeline@3/target/alpine-linux/aarch64/temurin/OpenJDK8U-jdk_aarch64_alpine-linux_hotspot_2022-10-01-12-06.tar.gz
root@c3-awx:/home/jenkins/.jenkins/workspace/build-scripts# 
```

**Comment by sxa** [comment]
It also looks like we're getting build-up of old artifacts in the workspaces, suggesting that things are not being correctly cleaned out - note the artifacts from the last two weeklies being left in the weekly pipeline's JDK11 workspace here:
```
root@c3-awx:/home/jenkins/.jenkins/workspace/build-scripts/weekly-openjdk11-pipeline/workspace# find . -name \*testimage_x64_linux\*gz -print
./OpenJDK11U-testimage_x64_linux_fast_startup_2022-09-17-17-05.tar.gz
./target/OpenJDK11U-testimage_x64_linux_hotspot_2022-09-10-17-05.tar.gz
./target/OpenJDK11U-testimage_x64_linux_fast_startup_2022-09-10-17-05.tar.gz
./OpenJDK11U-testimage_x64_linux_fast_startup_2022-10-01-17-05.tar.gz
./OpenJDK11U-testimage_x64_linux_fast_startup_2022-09-24-17-05.tar.gz
./OpenJDK11U-testimage_x64_linux_hotspot_2022-09-24-17-05.tar.gz
./OpenJDK11U-testimage_x64_linux_hotspot_2022-10-01-17-05.tar.gz
root@c3-awx:/home/jenkins/.jenkins/workspace/build-scripts/weekly-openjdk11-pipeline/workspace# 
```

**Comment by zdtsw** [comment]
we added the archive build from downstream job to weekly pipeline for future reproducible comparison to use.
this could be one reason it uses more space than months ago, but also we should try to disable jdk18 jobs once code froze is done.

**Comment by sxa** [comment]
We need to ensure that this build up does not occur. Ideally by clearing out these directories at the start of the weekly job so that this does not occur, as it looks from the directories here as though it's going to build up continuously:
```
root@c3-awx:/home/jenkins/.jenkins/workspace/build-scripts# find weekly* -name \*testimage_x64_linux\*gz -print
weekly-openjdk11-pipeline/workspace/OpenJDK11U-testimage_x64_linux_fast_startup_2022-09-17-17-05.tar.gz
weekly-openjdk11-pipeline/workspace/target/OpenJDK11U-testimage_x64_linux_hotspot_2022-09-10-17-05.tar.gz
weekly-openjdk11-pipeline/workspace/target/OpenJDK11U-testimage_x64_linux_fast_startup_2022-09-10-17-05.tar.gz
weekly-openjdk11-pipeline/workspace/OpenJDK11U-testimage_x64_linux_fast_startup_2022-10-01-17-05.tar.gz
weekly-openjdk11-pipeline/workspace/OpenJDK11U-testimage_x64_linux_fast_startup_2022-09-24-17-05.tar.gz
weekly-openjdk11-pipeline/workspace/OpenJDK11U-testimage_x64_linux_hotspot_2022-09-24-17-05.tar.gz
weekly-openjdk11-pipeline/workspace/OpenJDK11U-testimage_x64_linux_hotspot_2022-10-01-17-05.tar.gz
weekly-openjdk17-pipeline/OpenJDK17U-testimage_x64_linux_openj9_2022-09-11-12-05.tar.gz
weekly-openjdk17-pipeline/workspace/OpenJDK17U-testimage_x64_linux_hotspot_2022-09-25-12-05.tar.gz
weekly-openjdk17-pipeline/workspace/OpenJDK17U-testimage_x64_linux_openj9_2022-09-25-12-05.tar.gz
weekly-openjdk17-pipeline/OpenJDK17U-testimage_x64_linux_hotspot_2022-09-11-12-05.tar.gz
weekly-openjdk19-pipeline/workspace/OpenJDK19U-testimage_x64_linux_hotspot_2022-09-25-17-05.tar.gz
weekly-openjdk19-pipeline/OpenJDK19U-testimage_x64_linux_hotspot_2022-09-11-17-05.tar.gz
weekly-openjdk20-pipeline/OpenJDK-testimage_x64_linux_hotspot_2022-09-10-23-30.tar.gz
weekly-openjdk20-pipeline/workspace/OpenJDK-testimage_x64_linux_hotspot_2022-09-24-23-30.tar.gz
weekly-openjdk8-pipeline/workspace/OpenJDK8U-testimage_x64_linux_openj9_2022-09-17-12-05.tar.gz
weekly-openjdk8-pipeline/workspace/OpenJDK8U-testimage_x64_linux_openj9_2022-10-01-12-05.tar.gz
weekly-openjdk8-pipeline/workspace/target/OpenJDK8U-testimage_x64_linux_openj9_2022-09-10-12-05.tar.gz
weekly-openjdk8-pipeline/workspace/OpenJDK8U-testimage_x64_linux_openj9_2022-09-24-12-05.tar.gz
root@c3-awx:/home/jenkins/.jenkins/workspace/build-scripts# 
```

**Comment by sxa** [comment]
> we added the archive build from downstream job to weekly pipeline for future reproducible comparison to use. this could be one reason it uses more space than months ago, but also we should try to disable jdk18 jobs once code froze is done.

This is being left in the workspace, not as the result of the archiving which is stored elsewhere.
It's not being cleared up from the intermediate machine.

**Comment by sxa** [comment]
I have removed the weekly-openjdkXX-pipeline directories on the machine for 11, 17 and 19 for now and will re-run the weekly 17 pipeline, but this will need to be understood and fixed before the next weekly run otherwise we're running the risk of continually chewing up space in an uncontrolled manner. I can also see that the weekly pipelines do not appear to have passed for some time so that should also be investigated.

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/weekly-openjdk17-pipeline/88/console failed badly e.g. this is from one of the subjobs (https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/516/console):

```
[Pipeline] // load
[Pipeline] fileExists
[Pipeline] load
[Pipeline] { (/home/jenkins/.jenkins/workspace/build-scripts/openjdk17-pipeline@2/pipelines/jobs/configurations/jdk17u_pipeline_config.groovy)
[Pipeline] }
[Pipeline] // load
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: buildReference for class: WorkflowScript
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:471)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:355)
```

**Comment by zdtsw** [comment]
> https://ci.adoptopenjdk.net/job/build-scripts/job/weekly-openjdk17-pipeline/88/console failed badly e.g. this is from one of the subjobs (https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/516/console):
> 
> ```
> [Pipeline] // load
> [Pipeline] fileExists
> [Pipeline] load
> [Pipeline] { (/home/jenkins/.jenkins/workspace/build-scripts/openjdk17-pipeline@2/pipelines/jobs/configurations/jdk17u_pipeline_config.groovy)
> [Pipeline] }
> [Pipeline] // load
> [Pipeline] }
> [Pipeline] // node
> [Pipeline] End of Pipeline
> hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: buildReference for class: WorkflowScript
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:471)
> 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:355)
> ```

re-run weekly jdk17.
above failed reason is jenkins job/pipeline did not get regenerated successfully  due to "No space left on device" https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator/

**Comment by zdtsw** [comment]
looks like https://ci.adoptopenjdk.net/job/build-scripts/job/weekly-openjdk17-pipeline/89/console is working again.

**Comment by andrew-m-leonard** [comment]
i'll work on fixing this

**Comment by andrew-m-leonard** [comment]
The openjdk17-pipeline jobs were not cleaning their workspace at the end of the job, nor at the start which actually meant they could potentially pick up old builds.
The fix is to clean the workspace at the start and end.

I believe the following large workspaces can be deleted on C3jenkins:
```
build-scripts     111Gb
build-scripts-pr-tester   16Gb
SXA17-pipeline   6.7M
openjdk17-pipeline-SXA 6.7M
sophia_buildPipeline  1.2Gb
sophia_buildPipeline@tmp  4k
andrew-openjdk17-pipeline@tmp 4k
```
