### ISSUE TITLE
Exclude  "classes_nocoops.jsa" file from tar-ball when doing reproducible comparison

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#435]
**What are you trying to do?**
https://ci.adoptopenjdk.net/view/ReproducibleBuild/job/reproducible_comparision/ job when doing comparison with "diff" command should exclude "release" file which has build version info. etc are not identical
update: classes_nocoops.jsa is known non-deterministic issue at the moment. so it should be in the exclude list too. 

**Expected behaviour:**
comparison job should not fail because files in the excluded list are different from 2 tarball

**Observed behaviour:**
 "classes_nocoops.jsa" should not be listed
```
 diff -q -r url1Dir1 url1Dir2
Files url1Dir1/jdk-17.0.5+7/lib/server/classes.jsa and url1Dir2/jdk-17.0.5+7/lib/server/classes.jsa differ
Files url1Dir1/jdk-17.0.5+7/lib/server/classes_nocoops.jsa and url1Dir2/jdk-17.0.5+7/lib/server/classes_nocoops.jsa differ
Files url1Dir1/jdk-17.0.5+7/release and url1Dir2/jdk-17.0.5+7/release differ
```
**Any other comments:**
see https://github.com/adoptium/ci-jenkins-pipelines/issues/397#issuecomment-1269517946

**Comment by sakshi1215** [comment]
Hi @zdtsw Can you please assign me this issue?
