### ISSUE TITLE
Old Links: feature_request.md and not-sure-where-to-raise-an-issue.md need their links updating

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#443]
Regarding [feature_request.md](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) and [not-sure-where-to-raise-an-issue.md](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/.github/ISSUE_TEMPLATE/not-sure-where-to-raise-an-issue.md), both of these have links to the AdoptOpenJDK/TSC repository, which has been superseded by adoptium/adoptium.

Please replace the link in both files, and change "TSC repository" to "Adoptium repository" in both cases. 

Also, the "#dependent-projects" bit can be safely omitted. Or you can add that anchor to the adoptium/adoptium readme. Up to you.

**Comment by lumuchris256** [comment]
@adamfarley i would want to take this up

**Comment by adamfarley** [comment]
Have fun :)

**Comment by BarbaraStanley** [comment]
Please can I be assigned to this?

**Comment by lumuchris256** [comment]
> Please can I be assigned to this?

hi @BarbaraStanley 
i am working on this issue pushing a PR soonest
