### ISSUE TITLE
Broken Link: ARCHITECTURE.md needs three link updates

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#447]
ARCHITECTURE.md contains a set of URLs that begin "https://github.com/adoptium/temurin-build/tree/master", or the same URL with the word "blob" in place of "tree". As you can see, no resources exist at any of those three URLs.

Recommend updating the three URLs to point to the current locations for each of those resources. It's the same URL in each case, except "https://github.com/adoptium/temurin-build/blob(/tree)/master" is replaced by "..", as the three temurin-build links should all be updated to link to the ci-jenkins-pipelines repository (and changing them to relative paths prevents future issues).

**Comment by sakshi1215** [comment]
@adamfarley Can you please assign this to me?

**Comment by adamfarley** [comment]
Sure. Have fun. :)
