### ISSUE TITLE
Typo: ARCHITECTURE.md has three points for improvement

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#448]
ARCHITECTURE.md needs the word "Indiviual" changing to "Individual".

Also, the final close-parenthesis should be followed by a full stop for consistency.

Also also, the "This" under Individual Build Jobs should be "These".

**Comment by AyBims** [comment]
@smlambert @adamfarley can I be assigned to this issue

**Comment by adamfarley** [comment]
Thanks :)
