### ISSUE TITLE
Enhancement: Make ARCHITECTURE.md easier to read

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#449]
The sections for "Regenerate Jobs" and "Pipeline Jobs" have run-on sentences that tie my brain in knots. 

e.g. "These are the initial scripts that are the top level jobs that are invoked, etc etc"

I propose we break the sentences down into smaller sentences which are clearer.

e.g. "These are the initial scripts that are the top level jobs that are invoked," could be "These are the first scripts run by the top level jobs,", or similar. 

As a rule, this task is only complete once each sentence has two commas or less, and minimal redundancy.

**Comment by lumuchris256** [comment]
hi @adamfarley i can take this up, as i wait on scot to be back for my other issue am tackling
