### ISSUE TITLE
Typo: diagram.md contains a single typo

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#450]
"build all pass" should be "builds all pass".

**Comment by cornelia247** [comment]
please assign this to me @adamfarley

**Comment by adamfarley** [comment]
Okie dokie

**Comment by cornelia247** [comment]
please merge https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/438

**Comment by cornelia247** [comment]
please merge https://github.com/adoptium/ci-jenkins-pipelines/pull/463
