### ISSUE TITLE
Broken Links: UsingOurScripts.md has many broken "pipelines" links

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#451]
Inside UsingOurScripts.md, there are a great many links with relative paths, e.g. [here](pipelines/defaults.json).

However, because UsingOurScripts.md is inside the docs folder, that link ends up trying to take the user [here](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/docs/pipelines/defaults.json), which doesn't exist.

In short, please go through UsingOurScripts.md and add "../" to the start of every relative link that begins with "pipelines".

**Comment by lumuchris256** [comment]
hi @adamfarley  i would want to fix this

**Comment by adamfarley** [comment]
Sure @lumuchris256
