### ISSUE TITLE
remote trigger job did not pass down aqaReference 

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#457]
**What are you trying to do?**
Seems the job to be remote triggered by openjdkX-pipeline did not get set `ADOPTOPENJDK_BRACNH` correctly

**Expected behaviour:**

**Observed behaviour:**
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/217/consoleFull set `15:12:48  AQA tests Release/Branch name: v0.9.4-release`
but https://ci.eclipse.org/temurin-compliance/job/AQA_Test_Pipeline/91/parameters/ still got `master` to checkout

**Any other comments:**
https://github.com/adoptium/ci-jenkins-pipelines/blob/dff5839689766bbc3cb4c025773acb57f97a4f00/pipelines/build/common/build_base_file.groovy#L750

**Comment by zdtsw** [comment]
close issue with reason "chosen to use master branch because we may have needed to push a change to the framework that we needed in reaction to changes" 
so this is by design to not use aqaReference to run jobs in release test jenkins

**Comment by smlambert** [comment]
It is just currently not a requirement.  

aqaReference matters for AQAvit test suite as it helps pin to specific test material outlined in testenv.properties files in the release branch for the public test material we use.  

For TCK material, we use the test material that is downloaded from the partner site and there is one choice for us (the latest material downloaded by the EF infra team), so there is less reason for us to need to pin to a particular testenv.properties file for temurin-compliance runs.  We can still configure test jobs to use specific tags/branches/SHAs for the aqa-tests and TKG repository, but again, there is not much gain by doing that versus using master for those.
