### ISSUE TITLE
Broken Links: The regeneration README.md has many broken links

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#465]
Inside pipelines/build/regeneration/README.md, the links that begin with "pipelines" are all trying to send the user to a relative location that does not exist. 

Please add a forward slash before every link location that starts with "pipelines", as that will result in links that are relative to the root of the repository, rather than the README's location.

**Comment by cornelia247** [comment]
can I be assigned to this?
