### ISSUE TITLE
Discussion: Access permission to download artifacts from openjdkX-pipeline

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#490]
For permission in Jenkins [ci.adoptium.net](https://ci.adoptopenjdk.net/), any reason we have build jobs with public open access but not the others.

e.g https://ci.adoptopenjdk.net/job/build-scripts/job/weekly-openjdk19-pipeline/lastSuccessfulBuild/artifact/workspace/ is accessible even I do not login
e.g https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/lastSuccessfulBuild/artifact/workspace/target/ is the same, no need login but can download
But for e.g openjdkX-pipeline, only logged in user can download.

This creates a limitation for running  `reproducible_comparision` job 
if one of the URL given is from the openjdkX-pipeline it cannot download tarball
if they are from downstream(single build job), weekly pipeline job, or a link to github binary repo, all these cases are working

**Comment by smlambert** [comment]
Shouldn't the reproducible build comparison job use the temurin bot credentials (eclipse_temurin_bot_email_and_token) to access the necessary artifacts wherever they are?  Using that will remove the limited access.

Some JDK binaries (nightlies/EA) are produced with "this is Beta" written all over it, which means it is publicly accessible and not to be mistaken with a binary that is under-going extra testing and destined to be an official release (which should remain under restricted access until deemed ready for release).

**Comment by zdtsw** [comment]
close this issue:
- original problem to download artifacts from openjdkX-pipeline for comparison job has been resolved by using token
- currently we will not proceed with uploading artifacts from weekly builds into binary repo due to legal issues.
