### ISSUE TITLE
Discussion: naming convention for ciReference

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#495]
We should define what the git tag should be formed when we set it on [the](https://github.com/adoptium/ci-jenkins-pipelines) and used in the official release for input ciReference 

Since they will be used for reproducible build, unless we decided to use SHA instead of tag in the build, we should never move tags around. create new one if needed

Suggestion:` v<YY>.<MM>.01`
e.g for 2022 Oct CPU release, v2022.10.01 if any hot bug fix, we can create v2022.10.02 and so on.

DoD:
- what the name should be for tag
- be clear the process: who will apply such tag and when it should be done pre-release
- update https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version

Ref: https://github.com/adoptium/temurin-build/issues/3155

**Comment by zdtsw** [comment]
@andrew-m-leonard @smlambert @sxa @karianna any thoughts on this?

**Comment by andrew-m-leonard** [comment]
Maybe really spell the tag out a bit more for CPU releases? I like it when it is clear what the numbers means, eg:
BuildScripts_2022.Oct_CPU
BuildScripts_2022.Oct_CPU.01

**Comment by zdtsw** [comment]
we will use below format as a start:

- for trail test: vYYYY.MM.beforereleasetest
- for official tag:  vYYYY.MM.0X  (when X starts with 1 and can be increased for patch build)
