### ISSUE TITLE
Update the remote trigger jck tests jobs per platforms

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#499]
Currently AQA_Test_Pipeline job in Eclipse Temurin is remotely triggered by pipeline job when all platforms jdks are available. And then AQA_Test_Pipeline job will trigger all test jobs with all available jdks. It means all jck jobs can only be triggered when all platforms jdks are available. If some platform builds are slow then all tck jobs have to wait.

To run the jck test jobs ASAP we'd like to trigger the AQA_Test_Pipeline job per platform. So jck test jobs can be triggered as long as jdks are available.

**Comment by zdtsw** [comment]
preferably, [calling logic of remote trigger ](https://github.com/adoptium/ci-jenkins-pipelines/blob/eb6797c0c9d335830e5fa2268467f0e30c1f20a5/pipelines/build/common/build_base_file.groovy#L736)should be  right after [archive](https://github.com/adoptium/ci-jenkins-pipelines/blob/eb6797c0c9d335830e5fa2268467f0e30c1f20a5/pipelines/build/common/build_base_file.groovy#L844) is done by each downstream build job back to the openjdkX-pipeline. so the value of `TOP_LEVEL_SDK_URL`  will be pointing back to openjdk with longer retention.  
But if using the one from downstream job, that is acceptable too.

**Comment by sophia-guo** [comment]
So two options

1. right after [archive](https://github.com/adoptium/ci-jenkins-pipelines/blob/eb6797c0c9d335830e5fa2268467f0e30c1f20a5/pipelines/build/common/build_base_file.groovy#L844) , which will not wait for other platforms, but will wait until smoke and aqa-tests job finish. The pro is the sdk url will be the final one and will not be unavailable. The con is have to wait until smoke and aqa-tests jobs.
2. right after build jdk is available in downstream job. The pro is tck jobs can run  at the same time as aqa-tests jobs. The con is the sdk url will be unavailable when next build succeeds.

**Comment by zdtsw** [comment]
> So two options
> 
> 1. right after [archive](https://github.com/adoptium/ci-jenkins-pipelines/blob/eb6797c0c9d335830e5fa2268467f0e30c1f20a5/pipelines/build/common/build_base_file.groovy#L844) , which will not wait for other platforms, but will wait until smoke and aqa-tests job finish. The pro is the sdk url will be the final one and will not be unavailable. The con is have to wait until smoke and aqa-tests jobs.
> 2. right after build jdk is available in downstream job. The pro is tck jobs can run  at the same time as aqa-tests jobs. The con is the sdk url will be unavailable when next build succeeds.

Think we should go for option 2. 
Usually the AQA test for weekly/release can take longer than nightly and we do not want to wait for these hours.
