### ISSUE TITLE
Installer job node labels should be configurable

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/ci-jenkins-pipelines#50]
**🆕🐥🐶 First Timers Only**

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**
For the AdoptOpenJDK build we need some better configuration options for variables. Internally Groovy is used to executer parts of the CI build of AdoptOpenJDK. This part of the build should be configurable. Today some variables are still hard coded. This issue should refactor one of this parts:

https://github.com/AdoptOpenJDK/openjdk-build/blob/282058709909733381464dcb67b7f0d13dca4e13/pipelines/build/common/openjdk_build_pipeline.groovy#L323

This line of Groovy code contains 2 problems:
- [ ]  `fpm` label is hardcoded, could be parameterized.
- [ ]  It is assumed `TARGET_OS` will map directly to a label (`linux` for example). Not sure what the best way to parameterize that would be. I'm not actually sure why the lables are passed. Since these feed into 3 separate freestyle jobs, the jobs themselves could be configured to "Restrict where this project can be run".

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🎉 Contribute to Hacktoberfest**

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by Apurwa-Ghosh** [comment]
Hi, I am an Outreachy applicant. Can I work on this issue?

**Comment by M-Davies** [comment]
Sure. You are assigned 🙂 Let me know if you need any help at all

**Comment by andrew-m-leonard** [comment]
@AdamBrousseau is this relevant any more? thanks

**Comment by cornelia247** [comment]
@AdamBrousseau @smlambert  can this be assigned to me?

**Comment by andrew-m-leonard** [comment]
@cornelia247 Currently waiting for @AdamBrousseau feedback as to whether this is actually required?

**Comment by AdamBrousseau** [comment]
I'm not sure if this is still relevant. We've worked around the hardcoded label by adding an `if` condition in our fork of the code. Adopt has since removed the code in question and revamped how they do linux installers.
Here is what we did to avoid the hardcode
https://github.com/ibmruntimes/ci-jenkins-pipelines/blob/ibm/pipelines/build/common/openjdk_build_pipeline.groovy#L656-L660
```
        def nodeFilter = "${buildConfig.TARGET_OS}&&fpm"


        if (buildConfig.VARIANT == "openj9") {
            filter = "**/*-j*_${buildConfig.ARCHITECTURE}_${buildConfig.TARGET_OS}_*.tar.gz"
            nodeFilter = "sw.os.${buildConfig.TARGET_OS}&&ci.role.packaging&&sw.tool.rpm"
```

**Comment by andrew-m-leonard** [comment]
Thanks @AdamBrousseau
