### ISSUE TITLE
Feature: add 2nd build in nightly build so we can compare if 1st and 2nd are the same outcome

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#504]
For comparison job to work, we need two input builds.
~~What we have now is the [weekly build ](https://ci.adoptopenjdk.net/job/build-scripts/job/weekly-openjdk19-pipeline/)generates "release" type build which should work with reproducible if it is jdk17+~~

[ To make things simple, we start with jdk19, since jdk17 and 20 both running more than variant "temurin" so we should try to get other variants into "prototype" pipeline first. ]

since https://github.com/adoptium/temurin-build/pull/3166 has been implemented, so we can compare two builds from nightly build as long as they have the same input for` --build-reproducible-date`
The idea of this issue is to run a 2nd build and we can compare with the 1st (what we already have) but skip the nightly test on the 2nd one instead of calling [comparison job] 1st and the 2nd job should not be running on the same node, so we can have accurate result that the outcome as reproducible build is the same (https://ci.adoptopenjdk.net/view/ReproducibleBuild/job/reproducible_comparision/). 

[ For the time, we do not have reproducible for windows yet, so we should expect the result from comparison job is "red" if the OS is windows.]

NOW:
`nightly openjdk19->downstream jobs -> step build -> step sign -> step smoke ->  test1 /  test2 / test3 / ...`

WANT:
```
nightly openjdk19->downstream jobs-> step build1->step sign->step smoke->  test1 /  test2 / test3 / ...
                                   |-> step build2->step sign->step smoke-> comparison job
```

**Comment by andrew-m-leonard** [comment]
Replaced by https://github.com/adoptium/ci-jenkins-pipelines/pull/714
