### ISSUE TITLE
x86-64_alpine-linux test jobs fail due to DETECTED_JDK_VERSION mismatch from available artifact

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#508]
**What are you trying to do?**
Trying to launch jdk8 x64 alpine-linux testing.

**Expected behaviour:**
Expect to be able to successfully launch test pipelines as part of the build pipeline.

**Observed behaviour:**
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_x86-64_alpine-linux/99/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.functional_x86-64_alpine-linux/99/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_alpine-linux/35/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_x86-64_alpine-linux/108/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.perf_x86-64_alpine-linux/34/

All fail with
```
07:41:32  make -f makeGen.mk AUTO_DETECT=true MODE=buildList TESTTARGET=extended.functional TESTLIST=
07:41:32  make[1]: Entering directory '/home/jenkins/workspace/Test_openjdk8_hs_extended.functional_x86-64_alpine-linux/aqa-tests/TKG'
07:41:32  /home/jenkins/workspace/Test_openjdk8_hs_extended.functional_x86-64_alpine-linux/aqa-tests/TKG/envSettings.mk:32: *** DETECTED_JDK_VERSION value is 17, settled JDK_VERSION value is 8. JDK_VERSION value does not match. Please reset or unset JDK_VERSION.  Stop.
07:41:32  make[1]: Leaving directory '/home/jenkins/workspace/Test_openjdk8_hs_extended.functional_x86-64_alpine-linux/aqa-tests/TKG'
07:41:32  make: *** [makefile:80: buildListGen] Error 2
```

**Any other comments:**
The test job 
07:38:13  Copied 3 artifacts from "[build-scripts » jobs » jdk8u » jdk8u-alpine-linux-x64-temurin](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-alpine-linux-x64-temurin/)" build number [169](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-alpine-linux-x64-temurin/169/)

```
07:38:14  + ./get.sh -s /home/jenkins/workspace/Test_openjdk8_hs_extended.perf_x86-64_alpine-linux/aqa-tests/.. -p x86-64_alpine-linux -r upstream -j 8 -i hotspot --openj9_repo https://github.com/eclipse-openj9/openj9.git --openj9_branch master --tkg_repo https://github.com/adoptium/TKG.git --tkg_branch master
07:38:14  TESTDIR: /home/jenkins/workspace/Test_openjdk8_hs_extended.perf_x86-64_alpine-linux/aqa-tests
07:38:14  get jdk binary...
07:38:14  --sdkdir is set to upstream. Therefore, skip download jdk binary
07:38:14  Uncompressing file: OpenJDK8U-jdk_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz ...
07:38:16  Uncompressing file: OpenJDK8U-jre_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz ...
07:38:18  Uncompressing OpenJDK8U-debugimage_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz over ./j2sdk-image/jre...
07:38:23  Run /home/jenkins/workspace/Test_openjdk8_hs_extended.perf_x86-64_alpine-linux/openjdkbinary/j2sdk-image/bin/java -version
07:38:23  =JAVA VERSION OUTPUT BEGIN=
07:38:23  openjdk version "17.0.4.1" 2022-08-12
07:38:23  OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
07:38:23  OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
07:38:23  =JAVA VERSION OUTPUT END=
07:38:23  =RELEASE INFO BEGIN=
07:38:23  JAVA_VERSION="1.8.0_362"
07:38:23  OS_NAME="Linux"
07:38:23  OS_VERSION="2.6"
07:38:23  OS_ARCH="amd64"
07:38:23  SOURCE=".:git:730d6e3a1f55+"
07:38:23  IMPLEMENTOR="Eclipse Adoptium"
07:38:23  BUILD_SOURCE="git:73c1c00bdaa11a0ef333eee88dcd63b92c12c018"
07:38:23  BUILD_SOURCE_REPO="https://github.com/adoptium/temurin-build.git"
07:38:23  SOURCE_REPO="https://github.com/adoptium/jdk8u.git"
07:38:23  FULL_VERSION="1.8.0_362-b03"
07:38:23  SEMANTIC_VERSION="8.0.362+3"
07:38:23  BUILD_INFO="OS: Linux Version: 4.15.0-1113-azure"
07:38:23  JVM_VARIANT="Hotspot"
07:38:23  JVM_VERSION="25.362-b03"
07:38:23  IMAGE_TYPE="JDK"
07:38:23  =RELEASE INFO END=
```

**Comment by sophia-guo** [comment]
That's interesting. 
smoke test and sanity.openjdk passed without this issue.

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_alpine-linux/108/console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-alpine-linux-x64-temurin_SmokeTests/98/

```
07:38:24  Uncompressing file: OpenJDK8U-jdk_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz ...
07:38:27  Uncompressing file: OpenJDK8U-jre_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz ...
07:38:28  Uncompressing OpenJDK8U-debugimage_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz over ./j2sdk-image/jre...
07:38:34  Run /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_alpine-linux/openjdkbinary/j2sdk-image/bin/java -version
07:38:34  =JAVA VERSION OUTPUT BEGIN=
07:38:35  openjdk version "1.8.0_362"
07:38:35  OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b03)
07:38:35  OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b03, mixed mode)
07:38:35  =JAVA VERSION OUTPUT END=
07:38:35  =RELEASE INFO BEGIN=
07:38:35  JAVA_VERSION="1.8.0_362"
0
```

Build job was triggered by weekly pipeline. The suspected jdk is archived https://ci.adoptopenjdk.net/job/build-scripts/job/weekly-openjdk8-pipeline/97/artifact/workspace/OpenJDK8U-jdk_x64_alpine-linux_hotspot_2022-11-19-12-09.tar.gz

Run a grinder got same mismatch https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6233/

Feels like the jdk has been overriden after smoke tests and sanity.openjdk test jobs grab the jdk?

**Comment by smlambert** [comment]
Not sure if its related, but seems there is a long-standing issue where release script changes names/timestamps of artifacts and does not do it for alpine-linux, PR not yet merged: https://github.com/adoptium/github-release-scripts/pull/89

**Comment by sophia-guo** [comment]
Dup of #553
