### ISSUE TITLE
Update: nightlyBuildAndTestStatus job for release and evaluation pipepline

### ISSUE THREAD

**Issue by zdtsw** [adoptium/ci-jenkins-pipelines#550]
Since we introduced the new "release" and "evaluation" pipeline,
the current https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_temurin/ probably need to be updated accordingly.

Assume ${trssUrl}/api/getTopLevelBuildNames?type=Test will return all three kinds(?) once we have test job run, when we need a better filter (not only `contains('-pipeline')` )  to get data for different jdk version.

maybe a new section for evaluation (dont think release is needed to count)

**Comment by smlambert** [comment]
I was presuming that the release pipeline (openjdk17-release-pipeline) and evaluation pipeline (openjdk17-evaluation-pipeline) and nightly pipeline will be explicitly named differently, and I would update which pipelines we are monitoring in TRSS, so we could then query children independently:

https://trss.adoptopenjdk.net/api/getBuildHistory?buildName=openjdk17-release-pipeline

https://trss.adoptopenjdk.net/api/getBuildHistory?buildName=openjdk17-evaluation-pipeline

**Comment by zdtsw** [comment]
add to "2023 1Q",
could be a just quick verify, 

since the pipeline name has been changed
from openjdkX-evaluation-pipeline to evalucation-openjdkX-pipeline
same as for the release one

**Comment by andrew-m-leonard** [comment]
This has been superceded by issue: ﻿﻿﻿https://github.com/adoptium/ci-jenkins-pipelines/issues/746
