### ISSUE TITLE
A question about --docker parameter

### ISSUE THREAD

**Issue by Accelerator1996** [adoptium/ci-jenkins-pipelines#551]
I have a question about the --docker parameter. When we build a jdk, we will first run a docker container, then pull the temurin-build code, and then read various parameters, including the --docker parameter. But if this parameter is added, it will run docker command in the docker container. If the parameter is removed, BUILD_CONFIG[USE_DOCKER]  is false, however, it’s built with docker in fact. So is there something wrong with this?

**Comment by karianna** [comment]
@Accelerator1996 Is this the `--docker` switch in the make-any-jdk script from the temurin-build repo?

**Comment by Accelerator1996** [comment]
> @Accelerator1996 Is this the `--docker` switch in the make-any-jdk script from the temurin-build repo?

Yes.

**Comment by karianna** [comment]
IIRC - the --docker command for those build scripts is really designed for the developer desktop scenario where someone wants to build OpenJDK without impacting their host env.  For build farms we typically spin up a Docker image and run a 'typical' build.

**Comment by Accelerator1996** [comment]
> IIRC - the --docker command for those build scripts is really designed for the developer desktop scenario where someone wants to build OpenJDK without impacting their host env. For build farms we typically spin up a Docker image and run a 'typical' build.

As shown in the code, it will enter the docker container in the form of sidecar at the beginning of building jdk. Therefore, even if --docker is no longer used later, we are already in the docker container. That means we still use dockerbuild in the case of BUILD_CONFIG[USE_DOCKER] false.

> context.docker.image(buildConfig.DOCKER_IMAGE).inside(buildConfig.DOCKER_ARGS) {
>                                     buildScripts(
>                                         cleanWorkspace,
>                                         cleanWorkspaceAfter,
>                                         cleanWorkspaceBuildOutputAfter,
>                                         filename,
>                                         useAdoptShellScripts
>                                     )
>                                 }

**Comment by karianna** [comment]
@Accelerator1996  I've pinged our slack community for help - may be a little while given holidays for many

**Comment by Accelerator1996** [comment]
> @Accelerator1996 I've pinged our slack community for help - may be a little while given holidays for many

Thank you very much

**Comment by zdtsw** [comment]
for some of the platforms e.g x64 linux, aarch64 apline, we do build in a docker container. for the others, e.g s390x windows64, they cannot not build from docker container at all, so it is only the local env. ( if it is by jenkins, as you already checked `docker.image`, it is the agent where runs the jenkins docker plugin which in turn start a container)

I would say the name of the flag "--docker" (a.k.a BUILD_CONFIG[USE_DOCKER]) is not accurate.
Could be in the past, it was intended to use local VS an ephemeral docker container. 
but nowadays, by using this flag does not make much difference, if it should start a new container or not. 
the really important argument/flag to use is `DOCKER_IMAGE` , based on that then`DOCKER_ARGS` and so on.
see from https://github.com/adoptium/ci-jenkins-pipelines/blob/master/docs/diagram.md#breakdown-logic-of-build-script-buildcommonopenjdk_build_pipelinegroovy in the blue block "makejdk-any-platform"

As far as I am aware, we do not set or use` --docker `to BUILD_CONFIG in https://ci.adoptopenjdk.net/

**Comment by Accelerator1996** [comment]
> for some of the platforms e.g x64 linux, aarch64 apline, we do build in a docker container. for the others, e.g s390x windows64, they cannot not build from docker container at all, so it is only the local env. ( if it is by jenkins, as you already checked `docker.image`, it is the agent where runs the jenkins docker plugin which in turn start a container)
> 
> I would say the name of the flag "--docker" (a.k.a BUILD_CONFIG[USE_DOCKER]) is not accurate. Could be in the past, it was intended to use local VS an ephemeral docker container. but nowadays, by using this flag does not make much difference, if it should start a new container or not. the really important argument/flag to use is `DOCKER_IMAGE` , based on that then`DOCKER_ARGS` and so on. see from https://github.com/adoptium/ci-jenkins-pipelines/blob/master/docs/diagram.md#breakdown-logic-of-build-script-buildcommonopenjdk_build_pipelinegroovy in the blue block "makejdk-any-platform"
> 
> As far as I am aware, we do not set or use`--docker`to BUILD_CONFIG in https://ci.adoptopenjdk.net/

Thank you for your reply. In fact, my question comes from when I use the pipeline to generate sbom. The information about whether to use docker is affected by the above parameters, so it seems that the information of sbom is not accurate.

**Comment by zdtsw** [comment]
> > for some of the platforms e.g x64 linux, aarch64 apline, we do build in a docker container. for the others, e.g s390x windows64, they cannot not build from docker container at all, so it is only the local env. ( if it is by jenkins, as you already checked `docker.image`, it is the agent where runs the jenkins docker plugin which in turn start a container)
> > I would say the name of the flag "--docker" (a.k.a BUILD_CONFIG[USE_DOCKER]) is not accurate. Could be in the past, it was intended to use local VS an ephemeral docker container. but nowadays, by using this flag does not make much difference, if it should start a new container or not. the really important argument/flag to use is `DOCKER_IMAGE` , based on that then`DOCKER_ARGS` and so on. see from https://github.com/adoptium/ci-jenkins-pipelines/blob/master/docs/diagram.md#breakdown-logic-of-build-script-buildcommonopenjdk_build_pipelinegroovy in the blue block "makejdk-any-platform"
> > As far as I am aware, we do not set or use`--docker`to BUILD_CONFIG in https://ci.adoptopenjdk.net/
> 
> Thank you for your reply. In fact, my question comes from when I use the pipeline to generate sbom. The information about whether to use docker is affected by the above parameters, so it seems that the information of sbom is not accurate.

Ok, I see.
Yes, the fileds  in sbom.json related to `name" : "Use Docker for build",` or `"USE_DOCKER\" : \"false\",` are not correct if you use it that determinate if the build was done from a docker container or not.
Since they are derived directly from the build inputs (which is not accurate)
I have two old PR:s https://github.com/adoptium/temurin-build/pull/3045 and https://github.com/adoptium/ci-jenkins-pipelines/pull/365 to change it, I will try to see if we can get it fixed soon.

**Comment by Accelerator1996** [comment]
> > > for some of the platforms e.g x64 linux, aarch64 apline, we do build in a docker container. for the others, e.g s390x windows64, they cannot not build from docker container at all, so it is only the local env. ( if it is by jenkins, as you already checked `docker.image`, it is the agent where runs the jenkins docker plugin which in turn start a container)
> > > I would say the name of the flag "--docker" (a.k.a BUILD_CONFIG[USE_DOCKER]) is not accurate. Could be in the past, it was intended to use local VS an ephemeral docker container. but nowadays, by using this flag does not make much difference, if it should start a new container or not. the really important argument/flag to use is `DOCKER_IMAGE` , based on that then`DOCKER_ARGS` and so on. see from https://github.com/adoptium/ci-jenkins-pipelines/blob/master/docs/diagram.md#breakdown-logic-of-build-script-buildcommonopenjdk_build_pipelinegroovy in the blue block "makejdk-any-platform"
> > > As far as I am aware, we do not set or use`--docker`to BUILD_CONFIG in https://ci.adoptopenjdk.net/
> > 
> > 
> > Thank you for your reply. In fact, my question comes from when I use the pipeline to generate sbom. The information about whether to use docker is affected by the above parameters, so it seems that the information of sbom is not accurate.
> 
> Ok, I see. Yes, the fileds in sbom.json related to `name" : "Use Docker for build",` or `"USE_DOCKER\" : \"false\",` are not correct if you use it that determinate if the build was done from a docker container or not. Since they are derived directly from the build inputs (which is not accurate) I have two old PR:s [adoptium/temurin-build#3045](https://github.com/adoptium/temurin-build/pull/3045) and #365 to change it, I will try to see if we can get it fixed soon.

Thank you very much! Your PR solves the problem I want to solve.
