### ISSUE TITLE
Release pipeline generation make use of "USE_ADOPT_SHELL_SCRIPTS": false, which fails on Mac

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#571]
Release pipeline jobs use the "user" configuration pointing at the user remote tag/branch, but the necessary dual pass Mac eclipse-codesign depends on  "USE_ADOPT_SHELL_SCRIPTS": true.

**Comment by zdtsw** [comment]
so to not rush for a big change just before 2023 Jan release, propose to make a workaround for Mac release pipeline.
the idea is to: passing down USE_ADOPT_SHELL_SCRIPTS when `release-openjdkXX-pipeline` trigger downstream job 
`jdkXX u-release-mac-x64-temurin` and `jdkXXu-release-mac-aarch64-temurin`

so the jobs `jdkXX u-release-mac-x64-temurin` and `jdkXXu-release-mac-aarch64-temurin` will still use "master" branches from ci-jenkins-pipeline and temurin-build for this release.



We still need a proper long term solution for this fix.

**Comment by zdtsw** [comment]
some thoughts for future fix:
1.  less code change but add new step before release process
before we create release tag (e.g v2023.01.09) for ci-jenkins-pipeline and temurin-build and helper, we create a new commit to change the content of defaults.json (snippet and assume two new tags both called v2023.01.09)
from 
```
    "repository"             : {
        "build_url"          : "https://github.com/adoptium/temurin-build.git",
        "build_branch"       : "master",
        "test_dirs"          : "/test/functional",
        "pipeline_url"       : "https://github.com/adoptium/ci-jenkins-pipelines.git",
        "pipeline_branch"    : "master",
        "helper_ref"         : "master"
    },
```

to 
```
    "repository"             : {
        "build_url"          : "https://github.com/adoptium/temurin-build.git",
        "build_branch"       : "v2023.01.09",
        "test_dirs"          : "/test/functional",
        "pipeline_url"       : "https://github.com/adoptium/ci-jenkins-pipelines.git",
        "pipeline_branch"    : "v2023.01.09",
        "helper_ref"         : "v2023.01.09"
    },

```
along with changes from https://github.com/zdtsw/ci-jenkins-pipelines/tree/issue/571_2

in this case, we have USE_ADOPT_SHELL_SCRIPTS to true for all release pipelines and jobs

the branch names are defined in both DEFAULTS_JSON and ADOPT_DEFAULTS_JSON, we do not use the values set in USER_REMOTE_CONFIGS

Drawback of this is: the commit with changes in defaults.json cannot get merged into master. which means, release champion need to branch out from master, do the change, push to origin repo, tag it.  

2.  modify in ADOPT_DEFAULTS_JSON  and DEFAULTS_JSON by code
still need the change in https://github.com/zdtsw/ci-jenkins-pipelines/blob/issue/571_2/pipelines/build/regeneration/release_pipeline_generator.groovy
then in build_job_generator.groovy update `ADOPT_DEFAULTS_JSON` and `DEFAULTS_JSON`

```
ADOPT_DEFAULTS_JSON['repository']['pipeline_branch'] = ${params.REPOSITORY_BRANCH}
ADOPT_DEFAULTS_JSON['repository']['build_branch'] = ${params.REPOSITORY_BRANCH}
DEFAULTS_JSON['repository']['pipeline_branch'] = ${params.REPOSITORY_BRANCH}
DEFAULTS_JSON['repository']['build_branch'] = ${params.REPOSITORY_BRANCH}
```

need to add  support for DEFAULTS_JSON['repository']['helper_ref'] and ADOPT_DEFAULTS_JSON['repository']['helper_ref'] which is not setting in https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/release_pipeline_jobs_generator_jdkXXu yet

**Comment by andrew-m-leonard** [comment]
Workaround still fails: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-mac-x64-temurin/8/consoleFull

**Comment by andrew-m-leonard** [comment]
@zdtsw I think we should change to doing a release branch, like for aqa-tests, and we change defaults.json in it...

**Comment by zdtsw** [comment]
i think, https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-mac-x64-temurin/8/ was from the old run, not after last evening's regenerate.

**Comment by zdtsw** [comment]
i see the problem from last night's run, i will fix that.

**Comment by zdtsw** [comment]
> @zdtsw I think we should change to doing a release branch, like for aqa-tests, and we change defaults.json in it...

yeah, seems it is difficult to hijack USE_ADOPT_SHELL_SCRIPTS,
changed to set tag in defaults.json https://github.com/adoptium/ci-jenkins-pipelines/pull/576
