### ISSUE TITLE
Checksum file may be missing

### ISSUE THREAD

**Issue by Accelerator1996** [adoptium/ci-jenkins-pipelines#590]
The steps to generate checksum files are defined in each sign() method, but these are controlled by options similar to enableSigner. Logically speaking, the generation of sha256.txt should not be controlled by these, but should always be generated

**Comment by zdtsw** [comment]
If I understand you correctly, you are trying to generate `*.sha256.txt` as a default behavior even when `enableSigner` is not set to `true`

**Comment by Accelerator1996** [comment]
> If I understand you correctly, you are trying to generate `*.sha256.txt` as a default behavior even when `enableSigner` is not set to `true`

Yes, you are right. I think each of them should have a verification file.

**Comment by andrew-m-leonard** [comment]
@Accelerator1996 Can you point me to the scenario when no sha256.text is generated please? Do you have an example? As the base pipeline should do that:
https://github.com/adoptium/ci-jenkins-pipelines/blob/6b93fad7b37df5f2a50c6740c419b65d8f70b891/pipelines/build/common/build_base_file.groovy#L855

**Comment by Accelerator1996** [comment]
> @Accelerator1996 Can you point me to the scenario when no sha256.text is generated please? Do you have an example? As the base pipeline should do that:
> 
> https://github.com/adoptium/ci-jenkins-pipelines/blob/6b93fad7b37df5f2a50c6740c419b65d8f70b891/pipelines/build/common/build_base_file.groovy#L855

We use kick_off_build.groovy to build our jdk instead of openjdk_pipeline.groovy. Please take a look at this PR [link](https://github.com/adoptium/ci-jenkins-pipelines/pull/591/files). In the file pipelines/build/common/openjdk_build_pipeline.groovy, if enbaleSigner and enableInstallers are False, the checksum files will not be generated, but I think he should be able to generate it in any case.

**Comment by andrew-m-leonard** [comment]
> > @Accelerator1996 Can you point me to the scenario when no sha256.text is generated please? Do you have an example? As the base pipeline should do that:
> > https://github.com/adoptium/ci-jenkins-pipelines/blob/6b93fad7b37df5f2a50c6740c419b65d8f70b891/pipelines/build/common/build_base_file.groovy#L855
> 
> We use kick_off_build.groovy to build our jdk instead of openjdk_pipeline.groovy. Please take a look at this PR [link](https://github.com/adoptium/ci-jenkins-pipelines/pull/591/files). In the file pipelines/build/common/openjdk_build_pipeline.groovy, if enbaleSigner and enableInstallers are False, the checksum files will not be generated, but I think he should be able to generate it in any case.

kick_off_build.groovy is used in the "build" job (eg.build-scripts/job/jobs/job/jdk19u/job/jdk19u-linux-x64-temurin), but that is called by the top-level pipeline job which runs openjdk_pipeline.groovy (eg.build-scripts/job/openjdk19-pipeline/). The current sha256 generation is perhaps redundent in those methods.
I'll submit a test build pipeline with no signing and no installers, to check: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/293/

**Comment by Accelerator1996** [comment]
> > > @Accelerator1996 Can you point me to the scenario when no sha256.text is generated please? Do you have an example? As the base pipeline should do that:
> > > https://github.com/adoptium/ci-jenkins-pipelines/blob/6b93fad7b37df5f2a50c6740c419b65d8f70b891/pipelines/build/common/build_base_file.groovy#L855
> > 
> > 
> > We use kick_off_build.groovy to build our jdk instead of openjdk_pipeline.groovy. Please take a look at this PR [link](https://github.com/adoptium/ci-jenkins-pipelines/pull/591/files). In the file pipelines/build/common/openjdk_build_pipeline.groovy, if enbaleSigner and enableInstallers are False, the checksum files will not be generated, but I think he should be able to generate it in any case.
> 
> kick_off_build.groovy is used in the "build" job (eg.build-scripts/job/jobs/job/jdk19u/job/jdk19u-linux-x64-temurin), but that is called by the top-level pipeline job which runs openjdk_pipeline.groovy (eg.build-scripts/job/openjdk19-pipeline/). The current sha256 generation is perhaps redundent in those methods. I'll submit a test build pipeline with no signing and no installers, to check: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/293/

Thank you very much!

**Comment by andrew-m-leonard** [comment]
@Accelerator1996  Yes, sha256.txt files produced, : https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/293/artifact/target/windows/x64/temurin/

**Comment by Accelerator1996** [comment]
> @Accelerator1996 Yes, sha256.txt files produced, : https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/293/artifact/target/windows/x64/temurin/

Sorry, this project is invisible to me. According to the running time, I guess it is this task https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-windows-x64-temurin/63 , but I see that the artifact does not have sha256.txt.

**Comment by zdtsw** [comment]
it does not create in the downstream build job, but happens after downstream done and back in the pipeline. 

 in the  https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/293/artifact/target/windows/x64/temurin/ we have *sha256.txt but not in the https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-windows-x64-temurin/63

**Comment by Accelerator1996** [comment]
> it does not create in the downstream build job, but happens after downstream done and back in the pipeline.
> 
> in the https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/293/artifact/target/windows/x64/temurin/ we have *sha256.txt but not in the https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19u/job/jdk19u-windows-x64-temurin/63

Sorry, I only looked at the downstream project before and thought it was a bug.Thank you very much for your guidance! Thank you very much! @zdtsw @andrew-m-leonard
