### ISSUE TITLE
Mac codesign signing using eclipse-codesign does not check for success

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#596]
The Signing of Mac binaries by the eclipse-codesign service does not check each individual signing is successful
https://github.com/adoptium/ci-jenkins-pipelines/blob/e63be5b097685da73869cc18e5e077f310424689/pipelines/build/common/openjdk_build_pipeline.groovy#L1426

**Comment by steelhead31** [comment]
Think I have a potential fix for this, by examining each signed binary for the string "Apple Certification Authority" , built and unsigned binaries don't contain it...

**Comment by sophia-guo** [comment]
is this also an issue with https://github.com/adoptium/temurin-build/blob/master/sign.sh#L134 

https://github.com/adoptium/temurin-build/blob/master/sign.sh#L86  ?

**Comment by steelhead31** [comment]
> is this also an issue with https://github.com/adoptium/temurin-build/blob/master/sign.sh#L134
> 
> https://github.com/adoptium/temurin-build/blob/master/sign.sh#L86 ?

@sophia-guo I dont think we have seen the same error in the above two jobs ( but I think the underlying cause is volume related, in submitting a large number of requests in a short time ), however both of those curl requests use the --fail switch , so would likely fail "properly", and not carry on regardless. I will have a further look at those 2 scripts, and see if they could use the "retry" resilience. I've also added the --fail switch to the mac signing PR :)

**Comment by steelhead31** [comment]
Closed as Mac signing PR is now merged.

**Comment by adamfarley** [comment]
Heya @steelhead31 - Can I ask if the unannounced failures seen [here](https://ci.adoptium.net/job/build-scripts/job/release/job/sign_installer/9249/console) (or more accurately the apparent failure tro sign them [here](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-mac-x64-temurin/269/consoleFull), sans any report of failure) are being worked somewhere?

**Comment by adamfarley** [comment]
Thanks Scott!

**Comment by steelhead31** [comment]
Not related to Mac, but this shows a good example of the code signing service encountering an issue whilst doing the code signing..  
  
[https://ci.adoptium.net/job/build-scripts/job/release/job/sign_build/26029/console](https://ci.adoptium.net/job/build-scripts/job/release/job/sign_build/26029/console)  
  
`Signing ./bin/jfr.exe Signing ./bin/jfr.exe using Eclipse Foundation codesign service Signing ./bin/jhat.exe Signing ./bin/jhat.exe using Eclipse Foundation codesign service curl: (22) The requested URL returned error: 502 Build step 'Execute shell' marked build as failure`
