### ISSUE TITLE
jtreg() FAILED (every day)

### ISSUE THREAD

**Issue by ascheman** [adoptium/ci-jenkins-pipelines#606]
I see this broken Jenkins build every day in Slack

<img width="702" alt="image" src="https://user-images.githubusercontent.com/456000/216757446-61d1c9ca-2528-447e-8118-cd87f7417608.png">

Investigating, e.g., build no. [606](https://ci.adoptopenjdk.net/job/dependency_pipeline/696/consoleFull) it looks like the respective JDK is no longer installed (cf. #404):

<img width="578" alt="image" src="https://user-images.githubusercontent.com/456000/216757593-b4b524d1-e2d1-4f03-af71-ece78528272f.png">

I do not have access to the Jenkins machine but I guess jdk-11.0.16 as implemented in [tools/code-tools/jtreg.sh#L53](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/code-tools/jtreg.sh#L53) (by @sophia-guo) and [line 58](tools/code-tools/jtreg.sh#L58) (by @luhenry) was meanwhile replaced by a newer version?

Implementation ideas:
- Quick fix: Update the symlink `/usr/lib/jvm/jdk-11` (as shown in [this comment](https://github.com/adoptium/ci-jenkins-pipelines/issues/404#issuecomment-1245525654)) to the current JDK 11 (drawback: needs to be updated with any JDK update on the machine) and change the `jtreg.sh` sript accordingly.
- Compute one (if it does not matter) or the latest JDK 11 installation from the `jtreg.sh` script

**Comment by ascheman** [comment]
I wonder about the `mac` label as this problem is due to the chosen Jenkins build agent, could you please remove it?

**Comment by jerboaa** [comment]
@sxa Any thoughts about which stable JDK 11 path could be used for this job? We really ought to fix this broken jtreg job...

**Comment by jerboaa** [comment]
Last failing job seemed to have been run on [dockerhost-equinix-ubuntu2204-x64-1](https://ci.adoptium.net/computer/dockerhost%2Dequinix%2Dubuntu2204%2Dx64%2D1/), while the last successful one was also on [dockerhost-equinix-ubuntu2204-x64-1](https://ci.adoptium.net/computer/dockerhost%2Dequinix%2Dubuntu2204%2Dx64%2D1/)
