### ISSUE TITLE
Daily Build&Test Health does not check "mirrors" are Succeeding

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#615]
If the Adoptium mirrors https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/
are failing then we are building out of date code, currently:
- jdk8u not mirror'd for 14 days
- jdk11u not mirror'd for 6 days
-

**Comment by RadekCap** [comment]
I'm going to fix it. Currently, I'm not in some group so it isn't possible to assign me.

@andrew-m-leonard give me a piece of onboarding information so I know what is needed. I have to learn a few things but there is no pressure to fix it immediately.

The solution will be that in the message printed to Slack there will be three lines for jdk8 so the failure won't be hidden anymore.

**Comment by andrew-m-leonard** [comment]
@RadekCap try adding something like for each version...:
```
def version = "19u"
def mirrorJobLastSuccess = wget -q -O - ${jenkinsUrl}/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-skara-jdk${version}/lastSuccessfulBuild/api/json
def mirrorJobLastSuccessJson = new JsonSlurper().parseText(mirrorJobLastSuccess)
def lastSuccessTs = Instant.parse(mirrorJobLastSuccessJson.timestamp).atZone(ZoneId.of('UTC'))
def now = ZonedDateTime.now(ZoneId.of('UTC'))
def daysSinceLastSuccess = ChronoUnit.DAYS.between(lastSuccessTs, now)
```
