### ISSUE TITLE
Release build jobs are missing project security settings

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#618]
This folder needs project security settings: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/

**Comment by karianna** [comment]
@andrew-m-leonard permissions have been applied, PTAL

**Comment by karianna** [comment]
Do we need to do that for 8u, 11u, 17u, 20u and tip?

**Comment by andrew-m-leonard** [comment]
@karianna fyi, i've raised https://github.com/adoptium/temurin-build/issues/3306
to cover new jdk20u mirror and job changes...

**Comment by sxa** [comment]
NOTE: This still seems to be a problem - it looks like all of the release jobs are visible to all just now.

**Comment by zdtsw** [comment]
> NOTE: This still seems to be a problem - it looks like all of the release jobs are visible to all just now. Suggest this might be a priority before next week.

you are right! the change i made has a bug, which should not check on JENKINS_URL instead of JOB_NAME

**Comment by andrew-m-leonard** [comment]
Thank you for spotting that @zdtsw couldn't work out why they were still public!
