### ISSUE TITLE
Stop jdk19u builds and archive jobs

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#624]
Now jdk-19.0.2 is complete, no more builds are required, as jdk-20 supercedes.
We should disable jdk-19 nightlies and archive the jobs.

**Comment by jerboaa** [comment]
The nightly-publishing checker and corresponding slack notification job needs updates as well to move it to check JDK 20 over 19.

**Comment by adamfarley** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/pull/628

**Comment by adamfarley** [comment]
The CI pipeline repo has been updated [here](https://github.com/adoptium/ci-jenkins-pipelines/pull/628) and [here](https://github.com/adoptium/ci-jenkins-pipelines/pull/631) to remove jdk19u and to substitute jdk20 in its place.

Scott Fryer has agreed that this should be included in the release checklist, and has volunteered to make the relevant changes.

Next task: Figure out how to archive the jobs in a way that prevents them from being recreated the next time the jobs are refreshed.

**Comment by adamfarley** [comment]
Andrew has laid out the process, and has kindly volunteered to handle the final stage of this issue as I seem to lack the admin permissions needed to delete jobs.

**Comment by adamfarley** [comment]
The relevant jobs have been archived. I should also notify @steelhead31 that the changes to the source code required to fully retire a build in ci-jenkins-pipeline also seems to disable the thing that updates that pipeline automatically. Including the part of the update that *disables the nightly build schedule for that JDK version*.

So, to fully retire a pipeline, you also need to manually disable the pipeline job. Plus any other JDK-related Job disabling/deleting that may be needed.
