### ISSUE TITLE
Prevent standard build jobs from building type=Release

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#637]
Release builds should only be built using the release pipeline build jobs

**Comment by zdtsw** [comment]
move to "ci-jenkins-pipeline" repo, change will be done here

**Comment by zdtsw** [comment]
i will take a look at this one

**Comment by zdtsw** [comment]
is this still an open issue?

**Comment by andrew-m-leonard** [comment]
No this is fine, thanks
