### ISSUE TITLE
Upstream jdk-21 fork, and head moving to jdk-22

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#717]
Jdk-21 is forking to jdk21 repo June 8th 2023: https://mail.openjdk.org/pipermail/jdk-dev/2023-June/007894.html
Jdk(head) will become jdk-22

Specific jdk21 build jobs will need creating:
Tasks: https://github.com/adoptium/temurin-build/wiki/Setting-up-new-build-jobs,-mirrors,...-when-a-new-openjdk-version-is-branched-from-jdk(head)

**Comment by andrew-m-leonard** [comment]
Raised: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3252

**Comment by gdams** [comment]
@andrew-m-leonard, reminder that next time you need a new repo you can raise a PR to https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard, reminder that next time you need a new repo you can raise a PR to https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet

ah thanks @gdams , not sure how that works? Once that file is updated, does it automatically create the repo?

and do I need to retrospectively add adoptium/jdk21 to it?

**Comment by gdams** [comment]
> > @andrew-m-leonard, reminder that next time you need a new repo you can raise a PR to https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet
> 
> ah thanks @gdams , not sure how that works? Once that file is updated, does it automatically create the repo?
> 
> and do I need to retrospectively add adoptium/jdk21 to it?

It will eventually be automatic but right now the EF have to run a script once they've merged the changes. And no, you don't need to add jdk21, it will be automatically created in the jsonnet next time it's run.
