### ISSUE TITLE
Enable Weekend "Weekly" builds to run "dev...." test list

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#728]
Once PR https://github.com/adoptium/ci-jenkins-pipelines/pull/639/files is merged the weekend builds will run the "Weekly" test lists, which is currently “weeklyDefault” + “nightlyDefault”.

This issue will update "Weekly" to run: “weeklyDefault” + “nightlyDefault” + “devDefault”
Where "devDefault" is a new addition to the defaults.json testDetails lists: https://github.com/adoptium/ci-jenkins-pipelines/blob/04dda51e33ada01bca22e75626d2d4c7f1eb4ebb/pipelines/defaults.json#L39
And will contain:
        "devDefault"     : [
            "dev.openjdk",
            "dev.system"
        ]

Then the “test list” assignments for the various pipeline "ReleaseType" is:
ReleaseType==“Nightly” => “nightlyDefault”
ReleaseType==“Weekly” => “weeklyDefault” + “nightlyDefault” + “devDefault”
Releasetype==“Release” => “weeklyDefault” + “nightlyDefault”

Logic here: https://github.com/adoptium/ci-jenkins-pipelines/blob/04dda51e33ada01bca22e75626d2d4c7f1eb4ebb/pipelines/build/common/build_base_file.groovy#L241

**Comment by andrew-m-leonard** [comment]
Depends on https://github.com/adoptium/ci-jenkins-pipelines/pull/639/files

**Comment by andrew-m-leonard** [comment]
This will change when we consider moving to all version being EA tag build triggered, at which point the EA beta builds will run all the test including "dev", and Release builds will run all except for "dev".
The Weekly and nightly, terminology might also get refactored then.

**Comment by smlambert** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/pull/849 created a new testJobType explicitly for releases, so we can and have added dev level tests now.  Marking this as completed (though there will be a revision of what tests get run on which platforms as part of https://github.com/adoptium/ci-jenkins-pipelines/issues/857).
