### ISSUE TITLE
Enable windows reproducible build comparisons to Jenkins Pipelines

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/ci-jenkins-pipelines#743]
Part of https://github.com/adoptium/temurin-build/issues/3245, which needs to

- Test and update reproducible compare scripts under temurin-build/tooling/
- Update tools/reproduce_comparison/Jenkinsfile
- Turn on enableReproducibleCompare

**Comment by sophia-guo** [comment]
Signing and removing signature require `signtool` on windows seems adoptium windows agents do not have signtool installed. Should it be installed or we can use specific agent with signtool installed?

Also on jenkins windows agent I got the following two types errors. One is complaining modules is not a jimage file and other is not a jmod file. Both I have double check the files exist. @andrew-m-leonard any idea?

```
Error: not a jimage file: \cygdrive\f\workspace\workspace\Sophia_pipeline\temurin-build\tooling\..\..\original\jdk-17.0.8+6\lib\modules
Error: no jmod file found: \cygdrive\f\workspace\workspace\Sophia_pipeline\temurin-build\tooling\..\..\original\jdk-17.0.8+6\jmods\java.base.jmod
```

One is using jimage to expand the modules image 
The other one is using jmod to expand jmods


```

**Comment by andrew-m-leonard** [comment]
> Signing and removing signature require `signtool` on windows seems adoptium windows agents do not have signtool installed. Should it be installed or we can use specific agent with signtool installed?
> 
> Also on jenkins windows agent I got the following two types errors. One is complaining modules is not a jimage file and other is not a jmod file. Both I have double check the files exist. @andrew-m-leonard any idea?
> 
> ```
> Error: not a jimage file: \cygdrive\f\workspace\workspace\Sophia_pipeline\temurin-build\tooling\..\..\original\jdk-17.0.8+6\lib\modules
> Error: no jmod file found: \cygdrive\f\workspace\workspace\Sophia_pipeline\temurin-build\tooling\..\..\original\jdk-17.0.8+6\jmods\java.base.jmod
> ```
> 
> One is using jimage to expand the modules image The other one is using jmod to expand jmods
> 
> ```
> 
> ```

@sophia-guo that looks odd, i've only seen that error when the path was wrong

**Comment by sophia-guo** [comment]
Yes, that's what I suspect. I did some echo and the files are there. 
https://ci.adoptium.net/view/work-in-progress/job/Sophia_pipeline/448/console

```
+ ls -l /cygdrive/f/workspace/workspace/Sophia_pipeline/temurin-build/tooling/../../original/jdk-17.0.8+6/lib
total 184089
-rwxrwxr-x+ 1 jenkins None     73019 Jun 30 00:07 classlist
-rwxrwxr-x+ 1 jenkins None   8301490 Jun 30 00:07 ct.sym
-rwxrwxr-x+ 1 jenkins None      4630 Jun 30 00:07 fontconfig.bfc
-rwxrwxr-x+ 1 jenkins None     12345 Jun 30 00:07 fontconfig.properties.src
-rwxrwxr-x+ 1 jenkins None      1682 Jun 30 00:07 jawt.lib
drwxrwxr-x+ 1 jenkins None         0 Jun 30 00:07 jfr
-rwxrwxr-x+ 1 jenkins None    110513 Jun 30 00:07 jrt-fs.jar
-rwxrwxr-x+ 1 jenkins None        29 Jun 30 00:07 jvm.cfg
-rwxrwxr-x+ 1 jenkins None   1042840 Jun 30 00:07 jvm.lib
-rwxrwxr-x+ 1 jenkins None 128098045 Jun 30 00:07 modules
-rwxrwxr-x+ 1 jenkins None      3793 Jun 30 00:07 psfont.properties.ja
-rwxrwxr-x+ 1 jenkins None     11390 Jun 30 00:07 psfontj2d.properties
drwxrwxr-x+ 1 jenkins None         0 Jun 30 00:07 security
-rwxrwxr-x+ 1 jenkins None  50698817 Jun 30 00:07 src.zip
-rwxrwxr-x+ 1 jenkins None    103785 Jun 30 00:07 tzdb.dat
-rwxrwxr-x+ 1 jenkins None     22143 Jun 30 00:07 tzmappings
+ ls -l /cygdrive/f/workspace/workspace/Sophia_pipeline/temurin-build/tooling/../../original/jdk-17.0.8+6/jmods
total 74984
-rwxrwxr-x+ 1 jenkins None 19655369 Jun 30 00:06 java.base.jmod
-rwxrwxr-x+ 1 jenkins None   130570 Jun 30 00:04 java.compiler.jmod
...
```

The only difference between the path is one is using backslash and the other one is using foreward slash.

**Comment by sophia-guo** [comment]
signtool installed with window 10 sdk https://github.com/adoptium/infrastructure/blob/9c7b1e1d26395098459dbcc7e5e54cc6e1d5f9a4/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WiX/tasks/main.yml

Explicitly set signtool path signToolPath="/cygdrive/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64/signtool.exe" 

Remove signature `"$signToolPath" remove /s /v $f` got 

```
Removing signature from /cygdrive/e/jenkins/workspace/Sophia_pipeline/temurin-build/tooling/../../original/jdk-17.0.8+6/bin/jabswitch.exe
SignTool Error: Missing filename.
  ==> /cygdrive/e/jenkins/workspace/Sophia_pipeline/temurin-build/tooling/../../original/jdk-17.0.8+6/bin/jabswitch.exe contains no signature

```

Sign signature with generated openssl certificate alway failed.

**Comment by sophia-guo** [comment]
Quotes doesn't work either. Same issue with jmod and jimage. If cd the folder of the file and do the command works.

**Comment by sophia-guo** [comment]
From cygwin any paths pass to windows program jmod, jimage, signtool need to be in Windows (not cygwin) format. Need use cygpath to convert the path.

**Comment by sophia-guo** [comment]
Tried openssl to create self-signed certificates and works. 

```
  openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout $selfCert.key -out $selfCert.crt -subj "/CN=example.com" -addext "subjectAltName=DNS:example.com,DNS:*.example.com,IP:10.0.0.1"
  openssl pkcs12 -export -passout pass:test -out $selfCert.pfx -inkey $selfCert.key -in $selfCert.crt
```

**Comment by sophia-guo** [comment]
Interesting in jenkins windows using jmod and jimage to extract and nothing get extracted and return code is zero. In local windows cygwin no similar issue.
@andrew-m-leonard  any suggestion?

**Comment by sophia-guo** [comment]
Turns out the option --dir also need window path, otherwise the command succeeds with unexpected directory(slash removed)
