### ISSUE TITLE
Enable testing for Windows on ARM

### ISSUE THREAD

**Issue by aahlenst** [adoptium/ci-jenkins-pipelines#77]
Prerequisites:

* https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1977
* https://github.com/AdoptOpenJDK/openjdk-tests/issues/2224

**Comment by gdams** [comment]
We are currently working on procuring a machine to help unblock this

**Comment by gdams** [comment]
I have provisioned a Windows arm64 machine in Azure (https://github.com/adoptium/infrastructure/issues/2708) Closing
