### ISSUE TITLE
Trial the 'automatic rerun on failure' feature for test jobs

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#777]
Test jobs have an 'automatic rerun on failure' feature (https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L1216) which we should try using in our regular runs.

That feature is turned on via the RERUN_ITERATIONS parameter.  So in order to have it enabled, we can set that parameter in the jobs we trigger from the build pipeline (see https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L445-L462).

As a trial, we will minimally set RERUN_ITERATIONS=1 (if greater than 1, will launch in parallel, but let's not do that yet, but rather see if a simple rerun helps resolve intermittent failures we sometimes see).

**Comment by llxia** [comment]
We turned it on on selected test builds for Semeru. Here is an example: https://github.com/ibmruntimes/ci-jenkins-pipelines/blob/ibm/pipelines/build/common/openjdk_build_pipeline.groovy#L532
