### ISSUE TITLE
Support Adoptium "bootcycle-images" building to enhance reproducible builds and secure dev

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#815]
Investigate the option of building openjdk using the "bootcycle-images" target, see: https://openjdk.org/groups/build/doc/building.html

This builds the JDK twice, the first time with the user chosen BootJDK, and then the final time using the JDK it just built.
So in essence the resulting jdk-nn is built using the same jdk-nn as the BootJDK.

This could have some advantages for reproducible builds and secure-dev:
1) This aids reproducible builds for users, as it neutralises differences in the initial BootJDK used. Making identical reproducible builds easier.
2) The procedure is more secure against vulnerabilities in the user selected BootJDK.

**Comment by stooke** [comment]
Please note that the results of the bootcycle build (which I recommend as the final product of the build) appear in a different directory inside the ./build directory.

**Comment by andrew-m-leonard** [comment]
A potential issue, is also the way Adoptium signs embedded Mac jmod dylib's using a dual pass "exploded-image", then sign, then "assemble-image", which is potentially not comaptible with bootcycle.
This process will be added to Windows as well soon.

**Comment by andrew-m-leonard** [comment]
To alleviate the issue of jrt-fs.jar being non-reporducible with differen bootjdk, we need to investigate if upstream can re-build jrt-fs.jar after the "Build JDK" generation.

**Comment by andrew-m-leonard** [comment]
> To alleviate the issue of jrt-fs.jar being non-reporducible with different bootjdk, we need to investigate if upstream can re-build jrt-fs.jar after the "Build JDK" generation.

So we can't quite(!), as the "Build JDK" or more accurately the "interim compiler" used with the standard build which then compiles the product modules, is just a compiler, as jdk-11+ versions do not build any jars (other than jrt-fs.jar).
So although the jrt-fs classes can be compiled, the "jar" used to construct the jrt-fs.jar would be from the bootjdk.

**Comment by andrew-m-leonard** [comment]
The other option to consider, to address the enhancement of a secure "bootcycle", would be to simply do 2 builds, and pass the output JDK from the first into the 2nd via --with-boot-jdk=\<1st JDK\>

**Comment by andrew-m-leonard** [comment]
This issue has been mitigated upstream in jdk21+ by changing the jrt-fs build to use the interim compiler: https://github.com/openjdk/jdk21u/commit/e2b89c76e7fd87ecdfd2e208834996cccee106cb
