### ISSUE TITLE
Release pipelines are generated with CLEAN_WORKSPACE=false

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#835]
We should perform a clean for release builds, currently we're picking up the default used for nightlies.

Simple fix here:
https://github.com/adoptium/ci-jenkins-pipelines/blob/f3b15a4072b12ba61b0ff3d2aa480737a6ee856a/pipelines/jobs/release_pipeline_job_template.groovy#L89

**Comment by sxa** [comment]
Is there a reason - perhaps reproducibility related - not to use this for the non-release builds?
```
    "CLEAN_WORKSPACE": false,
    "CLEAN_WORKSPACE_AFTER": false,
    "CLEAN_WORKSPACE_BUILD_OUTPUT_ONLY_AFTER": true
```
I presume it was probably enabled set to true for the first two, but it strikes me that avoiding a full clone of the source repository would be a nice bonus in the non-release case and avoid chewing up a huge amount of bandwidth (and gain the potentially performance inprovements) by re-using the existing source?

**Comment by andrew-m-leonard** [comment]
Yes, we'd leave it as-is for non-release builds, so we don't clone openjdk every time...
We'd only do the change to the release pipeline template
