### ISSUE TITLE
Incorporate adoptium-packages-linux into Jenkins build pipelines

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#84]
This is a placeholder issue for initial incorporation of the adoptium-packages-linux work, based on the what @aahlenst has in https://github.com/aahlenst/adoptium-packages-linux. We would now like to be able to trigger build and test of these linux packages from Jenkins build pipelines.

As to where this gets triggered, see the diagram found in https://github.com/AdoptOpenJDK/TSC/issues/158#issuecomment-641708282, upon the creation of the JDK binaries, the installer pipeline can be triggered.  

Initial objective is to get building and testing of these packages running. https://github.com/aahlenst/adoptium-packages-linux/blob/main/NOTES.txt has some notes. This issue can (and should) encompass some remodelling effort to get rid of the large number of jobs.  It should also be standalone/modular enough to restart if failed (without a complete rerun of build pipelines / like test pipelines).  We can assume that this work will go through several iterations before its refined, but let's get some basic pipeline in place and then work on refinements.

Some further steps (which can be captured under a separate issue) can be to see whether we can publish into https://cloudsmith.com/ before adding more versions, more packages.

**Comment by smlambert** [comment]
I'll book time for a quick discussion on the initial approach with @sophia-guo and @aahlenst (likely Friday).

**Comment by sophia-guo** [comment]
Initial draft https://github.com/sophia-guo/ci-jenkins-pipelines/tree/installer working with jenkins build https://ci.adoptopenjdk.net/view/work-in-progress/job/adoptium-packages-linux/. There are some details need to be clarified. We will talk on Friday's meeting.

**Comment by aahlenst** [comment]
Thanks a lot, @sophia-guo. Do I see correctly that it's now part of the normal openjdk-build pipeline? I guess this makes things more complicated than needed because the packages do not depend on the openjdk-build pipelines (same as Docker). They are completely independent and on their own schedule. We will also have packages without a corresponding openjdk-build job (think IBM SDK).

**Comment by smlambert** [comment]
That may be my misrepresenting the requirements to @sophia-guo ... which is also why to connect with you Friday @aahlenst.  I understood that you wanted to incorporate this into the build pipelines.  Even easier should that not be the case.  Talk with you soon on the topic.

**Comment by karianna** [comment]
I'm late for the party here :-).  Is this intended to replace the existing openjdk-install based steps we have for producing Linux Packages, or is this something else?

**Comment by smlambert** [comment]
We are going to move the Jenkins changes that are currently in @sophia-guo's branch out of this repo and into https://github.com/aahlenst/adoptium-packages-linux so that the 'new' way of building installers can be standalone.  

The nice thing about the adoptium-packages-linux repo is that it contains testing for installers (via TestContainers).  I believe it will _eventually_ replace the existing openjdk-installer work, but there is more to do before we would reach that point.

**Comment by aahlenst** [comment]
>  Is this intended to replace the existing openjdk-installer based steps we have for producing Linux Packages.

Yes. The old code won't see any further development from me. I haven't officially deprecated it yet, because the new one isn't ready. I haven't created my intro write-up for the community discussion, either.

**Comment by zdtsw** [comment]
is this still a valid issue? or has it done

**Comment by karianna** [comment]
Still to be done (in terms of full automation)

**Comment by smlambert** [comment]
Closing this in favour of the installer overhaul being done under https://github.com/adoptium/installer/issues/1005
