### ISSUE TITLE
JDK22: zLinux: Extended.OpenJDK regularly times out and aborts

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#852]
**Summary**
Tests run very slow on this platform, and abort on most machines due to timeout. 

**Details**
Apparently this is par for the course for this test set. Past timeouts occurred on:
- [test-marist-ubuntu2204-s390x-1](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_s390x_linux_testList_0/7/consoleFull)
- [test-docker-sles12-s390x-1](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_s390x_linux_testList_0/8/)
- [test-marist-ubuntu2204-s390x-1](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_s390x_linux_testList_0/7/)
- [test-marist-sles15-s390x-2](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_s390x_linux_testList_0/3/)
- [test-marist-rhel7-s390x-2](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_s390x_linux_testList_0/1/)

And the sole pass happened on:
- [test-marist-rhel8-s390x-2](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_s390x_linux_testList_0/6/).

**Next steps**

I'm not seeing signs of a hang, just slow performance. Perhaps we could extend the timeout in this case?

**Comment by Haroon-Khel** [comment]
Id recommend 20hrs

**Comment by Haroon-Khel** [comment]
iirc there was another issue in the infra repo documenting extended openjdk timeouts. I cant find it at the moment. But this information should be added to that issue before closing this issue

**Comment by sxa** [comment]
We've got https://github.com/adoptium/infrastructure/issues/2662 regarding general machine-specific issues.

I'm not sure what that table comparing differnet platforms is showing us, but it doesn't seem to demonstrate the problem - was that data not from the slow runs we initially documented? Was there a reason for choosing jvm_compiler_? as the comparison?

@smlambert Was there a reason to transfer this from the tests to pipelines repository? I didn't think anything in here could have an influence over this, or does this control the timeout values somewhere for the extended.openjdk jobs?

**Comment by smlambert** [comment]
Transferred here because it is the right place to set TIME_LIMIT parameter so that it doesn't become 'unset' when/if test jobs are regenerated.

**Comment by sxa** [comment]
My last comment on here seems to have got lost. I thoght the jobs were created via [Test_Job_Auto_Gen](https://ci.adoptium.net/job/Test_Job_Auto_Gen/) which runs [aqatests -> testJobTemplate](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate). Where could we make a change in ci-jenkins-pipelines that would affect the `TIME_LIMIT` value in the generated test jobs?

**Comment by sxa** [comment]
Noting that this should also be applied for riscv64 where [sanity.openjdk](https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.openjdk_riscv64_linux/) can take around 17 hours on some of the systems.
Also extended.openjdk without Parallel=dynamic can take up to three days depending on the machine so I've been setting that to 100 when I've been running them (Although obviously there's good scope for running with Parallel=Dynamic in that case!)

**Comment by adamfarley** [comment]
Ok, I've put [this](https://github.com/adoptium/ci-jenkins-pipelines/pull/915) together to resolve this issue as advised, and to cover Stewart's riscv case.

[Here's a test run for zlinux.](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-s390x-temurin/14/)
[And another for riscv.](https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk21u/job/jdk21u-evaluation-linux-riscv64-temurin/129/)

Note: Both are queued, and will not exist until the previous job finishes.

**Comment by sxa** [comment]
@adamfarley It looks like you've done the PR for s390x but you've said it'll cover the riscv use case too. Have I missed something (quite possible - I'm reading this on my phone!)

**Comment by adamfarley** [comment]
@sxa - It should cover the riscv case as well. if-then-elseif.

**Comment by sxa** [comment]
Yeah LGTM - it that didn't seem to show that on my phone yesterday :-)
