### ISSUE TITLE
JDK11+: Special.OpenJDK fails to find tests associated with the target

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#868]
**What are you trying to do?**

JDK11+ Special.OpenJDK jobs cannot find any tests associated with the target, and these jobs then fail.

Example: https://ci.adoptium.net/job/Test_openjdk11_hs_special.openjdk_ppc64_aix/2/

```
18:22:34  Running special.openjdk ...
18:22:34  There is no test for target special.openjdk
```

**Details**

When the weekly pipelines run, the subsequent builds trigger post-build tests against various test targets.

Special.OpenJDK has been included in the default weekly tests since just before the 9th of December, but was not part of the [build pipeline testing prior to the 3rd](https://trss.adoptium.net/resultSummary?parentId=656b207920748f006f71427d).

It seems special.openjdk was added to the default list of tests for the weekly pipelines [here](https://github.com/adoptium/ci-jenkins-pipelines/commit/8f6ba6d2d213a51bdecdf085172db32fa3a11a3e).

Whether this is a typo, or part of a plan to have invalid test targets ignored/automatically-passed, is unclear.

FYI @smlambert

**Comment by smlambert** [comment]
I had seen it and plan to address it as part of https://github.com/adoptium/ci-jenkins-pipelines/issues/857 (applies to other versions also)

**Comment by adamfarley** [comment]
Ok then. Will close this. :)
