### ISSUE TITLE
Cannot invoke method unique() on null object affecting jdk11u x64 release pipeline

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/ci-jenkins-pipelines#894]
This pr, https://github.com/adoptium/ci-jenkins-pipelines/pull/886, was merged to the Jan 2024 [release branch](https://github.com/adoptium/ci-jenkins-pipelines/tree/v2024.01.01) to resolve a build error 

```
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: f2a762ce-4e70-4bdf-a9db-fb100d258499
java.lang.NullPointerException: Cannot invoke method unique() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
```
See https://ci.adoptium.net/job/build-scripts/job/release-openjdk11-pipeline/28/console

This error did not affect non release builds so it needs to be discussed as to whether this commit should be in master and a proper investigation is needed as to the cause of the error

**Comment by sophia-guo** [comment]
Non release builds won't be affected. However[ the commit ](https://github.com/adoptium/ci-jenkins-pipelines/commit/96c80efbddcaa26d90ece019ef701cec7034e9c7) should be in master as [default test configuration ](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/defaults.json#L39) works for most if not all platforms by now.

**Comment by sophia-guo** [comment]
However the [testlist logic ](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/build_base_file.groovy#L277-L284) is still need to be updated to work for this case.
