### ISSUE TITLE
Enable upstream build/tag driven nightly EA builds for Temurin jdk8,11,17

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#902]
Temurin jdk-21+ is already enabled for "build/tag driven nightly EA builds":
    https://ci.adoptium.net/job/build-scripts/job/utils/ 
      "**releaseTrigger_NNea**" jobs
We would now like to enable for all the Temurin jdk versions, and disable the scheduled nightly builds.
This will free up resource and capacity, especially with the approach of more versions to build from April 2024, and thus provide a more reliable and consistent build delivery.
The current nightly scheduled builds are typically re-building the same upstream last build, since the updates repositories are only pushed to from the "-dev" repos every week upon a new build being tagged.

These builds are triggered when an upstream OpenJDK new build tag is published (eg.**jdk-17.0.10+5**)

**They are triggered as:**
- Default version targetConfigurations (ie.the Temurin platforms list...)
- releaseType: "Weekly"
- scmReference: "\<Adopt build tag\>" (eg.**jdk-17.0.10+5_adopt**)
- overridePublishName: "\<Openjdk build tag\>-ea" (eg.**jdk-17.0.10+5-ea**)
- configureArgs: --with-version-opt=ea
- enableTests: True and using Weekly set

**Archive filenames as:**
- Timestamp field becomes "\<Openjdk build tag\>-ea" with "jdk-" prefix removed and + changed to _ 
    - eg. **_OpenJDK17U-debugimage_x64_linux_hotspot_17.0.10_5-ea.tar.gz_**
- No Filename renaming will occur from build to publish, hence signed SBOM SHA filenames will be correct

**Published as:**
- Tag: \<upstream build tag\>-ea-beta (eg.**jdk-17.0.10+5-ea-beta**)

**Comment by andrew-m-leonard** [comment]
Related: https://github.com/adoptium/temurin-build/issues/3450

**Comment by andrew-m-leonard** [comment]
Also enhancement to include: https://github.com/adoptium/ci-jenkins-pipelines/issues/776

**Comment by andrew-m-leonard** [comment]
jdk-21.0.3 needs re-enabling now that builds will be start being pushed weekly: https://wiki.openjdk.org/display/JDKUpdates/JDK+21u

**Comment by andrew-m-leonard** [comment]
To allow publishing nightly/beta archives with "-ea" in the timestamp/version: https://github.com/adoptium/github-release-scripts/pull/148

**Comment by sxa** [comment]
Noting that because of the way the pipelinesa re kicked off we don't currently auto-publish from the evaluation ones. We should aim to fix that too somehow (I had been been manually publishing them periodically with the parameters from the original 'ea'/'tag' issue) but that's clearly not sustainable.

**Comment by andrew-m-leonard** [comment]
PR: https://github.com/adoptium/ci-jenkins-pipelines/pull/914

**Comment by andrew-m-leonard** [comment]
Note: The schedule for the "betaTrigger_NNea" jobs may want to exclude release preiods, to avoid triggering the release tag prior to it being marked "-ga", however typically the "-ga" is added fairly close to the release publish so we may need not do that.
