### ISSUE TITLE
WIP: Bug: Nightly tests can be re-enabled during a release if you merge a pr in ci-jenkins-pipelines

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#903]
Nightly tests are disabled during releases. However if a PR in ci-jenkins-pipeline is merged during a release, the tests will be re-enabled again as the jobs are regenerated.

_Originally posted by @sophia-guo in https://github.com/adoptium/temurin/issues/13#issuecomment-1914789028_

**Comment by andrew-m-leonard** [comment]
We no longer have nightly builds, replaced by tag triggered EA builds which have automatic release disabling of Testing. This is thus no longer required. Doc updates issue will cover this in the checklist: https://github.com/adoptium/temurin-build/issues/3665
