### ISSUE TITLE
Request to remove the alpine JCK automanuals jtx file

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#919]
Request to remove the alpine automanuals `.jtx` file.

Originally requested by @sxa, and discussed in the TCK retrospective - https://github.com/temurin-compliance/temurin-compliance/issues/453#issuecomment-1900349455

Note: This was specifically requested to be created in this repository.

**Comment by sxa** [comment]
> Note: This was specifically requested to be created in this repository.

Any idea why?

**Comment by adamfarley** [comment]
> > Note: This was specifically requested to be created in this repository.
> 
> Any idea why?

Not off the top of my head, no. Maybe it was because putting this in a non-restricted repo makes it easier to track?

**Comment by smlambert** [comment]
The change can happen in this repo (dropping the APPLICATION_OPTIONS parameter for alpine-linux after https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L528), as in:

if (platform.contains("alpine-linux")) {
    appOptions=""
}

**Comment by sxa** [comment]
> Even better would be a check for whether a platform is headless, and if so, appOptions="" (which will run all tests as automated, not excluding some to be run as 'automanuals').

Yep agreed - since riscv64 will (at least initially) be in that category that would be a better option.
