### ISSUE TITLE
Github linter failure due to methods count in build base file being 31

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#925]
The linter warning is the methods is 31, the default maxMethods=30 https://codenarc.org/codenarc-rules-size.html#methodcount-rule

_Originally posted by @sophia-guo in https://github.com/adoptium/ci-jenkins-pipelines/issues/923#issuecomment-1939720738_

**Comment by karianna** [comment]
Should that shell script really have more than 30 methods?  Probably not...

**Comment by sophia-guo** [comment]
Fixed by #931 https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/build_base_file.groovy#L15
