### ISSUE TITLE
`_testList` and `_rerun` jobs are not periodically regenerated

### ISSUE THREAD

**Issue by sxa** [adoptium/ci-jenkins-pipelines#936]
> There are two other types of test jobs naming as `_testList_` and `_rerun`. Those jobs are generated if no jobs exist or if test job parameter `GENERATE_JOBS` is true, which currently can't be set by upstream weekly pipeline unless we add extra parameter.

_Originally posted by @sophia-guo in https://github.com/adoptium/infrastructure/issues/2774#issuecomment-1949387541_
            
Creating this issue as a preferable long term fix is to look at ensuring that all the `_testList` and `_rerun` jobs are regenerated at the same time as the top level test jobs that run them, otherwise they will be out of date and have inconsistent parameters with the caller.

**Comment by sophia-guo** [comment]
Double checked. We did set GENERATE_JOBS=aqaAutoGen https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L464 . So _testlist and _rerun jobs are also periodically regenerated. Not sure why there is warning with _testList or _rerun mentioned https://github.com/adoptium/infrastructure/issues/2774#issuecomment-1954526480 . Need more investigation. Close this.

**Comment by sxa** [comment]
> @sxa the current weekly regen works for the weekly-openjdkXX-pipeline.
> 
> _testlist and _rerun jobs can be regenerated as long as we set aqaAutoGen=true. My former comment was wrong and that's why I double checked. Sorry for confusion.

OK that's good to know (I didn't need to delete all the testList jobs yesterday after all.

If regen is only set for weekly-openjdkXX-pipeline It sounds like this needs to be reopened if we need to add an option into the tagged builds to enable regeneration generally (Could be another issue but this one was to cover having all the regular regenerations in place that are required)

FYI @andrew-m-leonard

**Comment by sophia-guo** [comment]
Seems now tagged builds always trigger[ releaseType=weekly](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/trigger_beta_build.groovy#L171). In that case if we really need to regen all test jobs for each pipeline run, can simply add `booleanParam(name: 'aqaAutoGen',       value: true)` as [jobParams ](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/trigger_beta_build.groovy#L170).

**Comment by sophia-guo** [comment]
As test job params don't change frequently not sure if it is necessary to regen everytime. The regen does take time and resources. Meanwhile if we do regen everytime we might just remove the `aqaAutoGen` as parameter of pipeline and build jobs, which can be set directly in [runAqaTests](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L369)

**Comment by sxa** [comment]
> Seems now tagged builds always trigger[ releaseType=weekly](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/trigger_beta_build.groovy#L171). In that case if we really need to regen all test jobs for each pipeline run, can simply add `booleanParam(name: 'aqaAutoGen', value: true)` as [jobParams ](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/trigger_beta_build.groovy#L170).

Based on a conversation today it sounds like the regen is NOT triggered unless it's from the weekly-* pipelines, so there will be some work to enable regeneration in the beta triggered builds which have `releaseType=weekly` but aren't run via the `weekly-openjdkXX-pipeline` jobs.

**Comment by sophia-guo** [comment]
> Seems now tagged builds always trigger[ releaseType=weekly](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/trigger_beta_build.groovy#L171). In that case if we really need to regen all test jobs for each pipeline run, can simply add booleanParam(name: 'aqaAutoGen', value: true) as [jobParams ](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/trigger_beta_build.groovy#L170).

This is the solution for beta trigger builds regen test jobs, which is better than the changes in runAQATest() as this solution won't affect other vendor.  @sxa

**Comment by sxa** [comment]
Thanks @sophia-guo - I think we're all sorted for the future with your PR!
