### ISSUE TITLE
JDK22+ Mac x64 builds cannot be tested on MacOS versions below 11

### ISSUE THREAD

**Issue by adamfarley** [adoptium/ci-jenkins-pipelines#949]
**What are you trying to do?**

Ensure all JDK22+ Mac x64 tests are run with a node label that excludes the one MacOS test node using a version under 11.

**Expected behaviour:**

The node label for all testing should include a "!sw.os.osx.10_14".

**Observed behaviour:**

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-mac-x64-temurin/15/

We fail when we get to the smoke tests on a 10.14 machine. Error message:

```
00:43:53  =JAVA VERSION OUTPUT BEGIN=
00:43:53  dyld: lazy symbol binding failed: Symbol not found: _objc_opt_respondsToSelector
00:43:53    Referenced from: /Users/jenkins/workspace/build-scripts/jobs/jdk22/jdk22-mac-x64-temurin_SmokeTests/jdkbinary/j2sdk-image/Contents/Home/lib/libjava.dylib (which was built for Mac OS X 11.0)
00:43:53    Expected in: /usr/lib/libobjc.A.dylib
```

**Any other comments:**

Discovered [here](https://github.com/adoptium/temurin-build/issues/3669), discussed [here](https://adoptium.slack.com/archives/C53GHCXL4/p1709135385218959), and documented [here](https://github.com/adoptium/adoptium.net/issues/2693#issuecomment-1969378622).

**Comment by adamfarley** [comment]
Draft PR created [here](https://github.com/adoptium/ci-jenkins-pipelines/pull/950), which was based on this fix [here](https://github.com/adoptium/ci-jenkins-pipelines/pull/622/files).

Being tested here: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-mac-x64-temurin/18/console

**Comment by adamfarley** [comment]
The additional test label isn't being passed down to the smoke test job.

I'm running a debug job [here](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-mac-x64-temurin/19/console) to make sure the variable is correctly read from the config file, and while that runs I plan to read the smoke test launching code to see if we're trying to use the additional test label.

**Comment by smlambert** [comment]
To resolve the issue described in https://github.com/adoptium/ci-jenkins-pipelines/issues/949#issuecomment-1973117812, try adding
`context.string(name: 'LABEL_ADDITION', value: additionalTestLabel),`
to this [section of code](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L325-L339).

**Comment by adamfarley** [comment]
Thanks Shelley. I think it's already there, I just wasn't running my modified code due to the hard-coded pipeline repo/branch value for ci-jenkins-pipeline. I've hit this before, I just forgot about it.

My rerun [here](https://ci.adoptium.net/job/build-scripts/job/openjdk22-pipeline/128/console) definitely uses my modified code.

**Comment by adamfarley** [comment]
Ok, that works! Requesting reviews now.

**Comment by adamfarley** [comment]
PR merged, issue closed.
