### ISSUE TITLE
Improve Success Rating output to better describe scenarios where tests not run

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#97]
**👾 Description of the issue**

We have a [nightly_build_and_test_stats.groovy](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/tools/nightly_build_and_test_stats.groovy) file that reports a success rating. 

It's been shown recently during the release where we turn off Nightly Tests that the success rating figure drops immediately to 50%, as the value is currently (BuildSuccessRating+TestSuccessRating)/2.
We need to make it more useful in these scenarios.  We should improve the message that is sent to the build Slack channel (see https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/master/tools/nightly_build_and_test_stats.groovy#L182).

This is the current style of message sent to the build Slack channel: 
<img width="737" alt="Screen Shot 2021-03-30 at 7 57 39 PM" src="https://user-images.githubusercontent.com/2836948/113071231-514a2b00-9192-11eb-90d3-c9dd591468a9.png">

Suggestions:
- Output Slack msg containing both the Build and Test ratings separately, and also indicate when no Tests have run
- Better message examples:
```
"Adoptium Pipeline report: 98% (derived from 160 build jobs at 98%, 0 test jobs at n/a %)"
Alternatively
"Adoptium Pipeline report: 82% (derived from 158 build jobs at 97%, 201 test jobs at 68%)"
```
- Hyperlink to the jenkins job from the Slack message so people can dig into the detail if needed.
 
**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [x]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by ellschi** [comment]
I would like to be assigned for this issue. Thanks in advance!

**Comment by ellschi** [comment]
Okay, as I found this one very understandable I commited my changes and started a pull request before waiting to be assigned. I hope that's okay! Looking forward to a review!

**Comment by smlambert** [comment]
Very good, thanks @ellschi !

**Comment by andrew-m-leonard** [comment]
@ellschi Hi there, how are you getting on with this? do you need any help?

**Comment by M-Davies** [comment]
> Okay, as I found this one very understandable I commited my changes and started a pull request before waiting to be assigned. I hope that's okay! Looking forward to a review!

@ellschi Looks like you created a pull request against your own repository for this issue https://github.com/ellschi/ci-jenkins-pipelines/pull/1. To be able to merge the code into the branch of this main repository (not your fork), you need to:
1. Go to https://github.com/adoptium/ci-jenkins-pipelines/compare
2. Hit `compare across forks`
3. Select your repo and branch that contains the changes you made on the right. Verify that the repo and branch on the left are `adoptium/ci-jenkins-pipelines` and `master`
4. Hit create!

This will open a [pull request in this repository](https://github.com/adoptium/ci-jenkins-pipelines/pulls) for us to review, comment on and merge. Let me know if you need any help with that 🙂

**Comment by andrew-m-leonard** [comment]
Thanks @M-Davies for helping
