### ISSUE TITLE
Enable building Temurin jdk-21.0.3+ using gcc 11.3.0 DevKit for x64/aarch64/ppc64le/s390x

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#977]
As part of the Eclipse Adoptium secure dev [Reproducible build support](https://github.com/adoptium/temurin-build/issues/3468#issuecomment-1706753618), we would like to update Temurin jdk-21.0.3+ builds to be built using the gcc 11.3.0 DevKit for platforms x64/aarch64/ppc64le/s390x.

Upstream OpenJDK jdk21u/jdk22 build maintainers (SAP) already build these platforms using gcc 11.3.0 (devkit).

The plan is to upgrade at least x64/aarch64/ppc64le for jdk-21.0.3 as they are easily built on Centos7. s390x is a bit more tricky since there isn't a Centos7 port for s390x.

**Comment by jerboaa** [comment]
Discussed at the PMC meeting on March 20. Agreed to proceed with this proposal.

**Comment by andrew-m-leonard** [comment]
Completed
