### ISSUE TITLE
Missing parameters in remoteTriggerJckTests

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#980]
There are additional parameters needed for successful remote triggering of test jobs on the remote temurin-compliance server 

See:
https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L601-L612

- we should percolate the AUTO_AQA_GEN=true (for the cases where the test jobs do not exist
- we likely should set the JCK_GIT_REPO (or as a default setting in the AQA_Test_Pipeline in the remote server
- check any other params that are best to explicitly set rather than expect correct defaults

**Comment by sophia-guo** [comment]
> we likely should set the JCK_GIT_REPO (or as a default setting in the AQA_Test_Pipeline in the remote server

The JCK_GIT_REPO can not be set as a default in the AQA_Test_Pipeline in the remote server as we need to support different versions. To set the JCK_GIT_REPO by remote I'm not sure if JCK_GIT_REPO can be set | visible outside of temurin-compliance.

We might also need to update the logic of test generation of https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/aqaTestPipeline.groovy before percolate the AUTO_AQA_GEN=true. As currently the logic is generate the job if AUTO_AQA_GEN=true no matter test jobs exist or not.
